/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.seguridad;

import java.awt.Color;
import javax.swing.JButton;
import ui.login.Login;

/**
 *
 * @author Nicolas
 */
public class SeguridadFrame extends javax.swing.JFrame {
    
    
    Color colorBotonPresionado = new Color(108, 136, 69);

    Color colorBotonProveedorPresionado = new Color(153, 195, 84);

    /**
     * Creates new form SeguridadFrame
     */
    public SeguridadFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionarAreaSeguridad = new javax.swing.JButton();
        btnGestionarRobos = new javax.swing.JButton();
        btnCerrarSesionSeguridad = new javax.swing.JButton();
        btnGestionarIncidentes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelGeneralSeguridad = new javax.swing.JTabbedPane();
        panelGestionarAreaSeguridad = new javax.swing.JPanel();
        panelGestionarIncidentes = new javax.swing.JPanel();
        panelGestionarRobos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1400, 880));
        setMinimumSize(new java.awt.Dimension(1400, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnGestionarAreaSeguridad.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarAreaSeguridad.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarAreaSeguridad.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarAreaSeguridad.setText("     Gestionar área");
        btnGestionarAreaSeguridad.setBorder(null);
        btnGestionarAreaSeguridad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarAreaSeguridad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarAreaSeguridadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarAreaSeguridadMouseExited(evt);
            }
        });
        btnGestionarAreaSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarAreaSeguridadActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarAreaSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 280, 50));

        btnGestionarRobos.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarRobos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarRobos.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarRobos.setText("     Gestionar robos");
        btnGestionarRobos.setBorder(null);
        btnGestionarRobos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarRobos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarRobosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarRobosMouseExited(evt);
            }
        });
        btnGestionarRobos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarRobosActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarRobos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 50));

        btnCerrarSesionSeguridad.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesionSeguridad.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnCerrarSesionSeguridad.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesionSeguridad.setText("     Cerrar sesión");
        btnCerrarSesionSeguridad.setBorder(null);
        btnCerrarSesionSeguridad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesionSeguridad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionSeguridadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionSeguridadMouseExited(evt);
            }
        });
        btnCerrarSesionSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionSeguridadActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesionSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 280, 50));

        btnGestionarIncidentes.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarIncidentes.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarIncidentes.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarIncidentes.setText("     Gestionar incidentes");
        btnGestionarIncidentes.setBorder(null);
        btnGestionarIncidentes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarIncidentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarIncidentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarIncidentesMouseExited(evt);
            }
        });
        btnGestionarIncidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarIncidentesActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarIncidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 880));

        jPanel3.setBackground(new java.awt.Color(108, 136, 69));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Seguridad");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1320, 110));

        panelGeneralSeguridad.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        javax.swing.GroupLayout panelGestionarAreaSeguridadLayout = new javax.swing.GroupLayout(panelGestionarAreaSeguridad);
        panelGestionarAreaSeguridad.setLayout(panelGestionarAreaSeguridadLayout);
        panelGestionarAreaSeguridadLayout.setHorizontalGroup(
            panelGestionarAreaSeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1067, Short.MAX_VALUE)
        );
        panelGestionarAreaSeguridadLayout.setVerticalGroup(
            panelGestionarAreaSeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        panelGeneralSeguridad.addTab("tab1", panelGestionarAreaSeguridad);

        javax.swing.GroupLayout panelGestionarIncidentesLayout = new javax.swing.GroupLayout(panelGestionarIncidentes);
        panelGestionarIncidentes.setLayout(panelGestionarIncidentesLayout);
        panelGestionarIncidentesLayout.setHorizontalGroup(
            panelGestionarIncidentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1067, Short.MAX_VALUE)
        );
        panelGestionarIncidentesLayout.setVerticalGroup(
            panelGestionarIncidentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        panelGeneralSeguridad.addTab("tab2", panelGestionarIncidentes);

        javax.swing.GroupLayout panelGestionarRobosLayout = new javax.swing.GroupLayout(panelGestionarRobos);
        panelGestionarRobos.setLayout(panelGestionarRobosLayout);
        panelGestionarRobosLayout.setHorizontalGroup(
            panelGestionarRobosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1067, Short.MAX_VALUE)
        );
        panelGestionarRobosLayout.setVerticalGroup(
            panelGestionarRobosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        panelGeneralSeguridad.addTab("tab3", panelGestionarRobos);

        jPanel1.add(panelGeneralSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 1120, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void botonPresionado(JButton boton) {

        boton.setBackground(colorBotonPresionado);

        boton.setForeground(Color.white);

    }

    public void botonDespresionado(JButton boton) {

        boton.setBackground(Color.white);

        boton.setForeground(Color.BLACK);

    }

    public void botonProveedorDespresionado(JButton boton) {

        boton.setBackground(colorBotonProveedorPresionado);

        boton.setForeground(Color.BLACK);

    }
    private void btnGestionarAreaSeguridadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarAreaSeguridadMouseEntered
        botonPresionado(btnGestionarAreaSeguridad);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarAreaSeguridadMouseEntered

    private void btnGestionarAreaSeguridadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarAreaSeguridadMouseExited
        botonDespresionado(btnGestionarAreaSeguridad);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarAreaSeguridadMouseExited

    private void btnGestionarAreaSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarAreaSeguridadActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarAreaSeguridadActionPerformed

    private void btnGestionarRobosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarRobosMouseEntered
        botonPresionado(btnGestionarRobos);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarRobosMouseEntered

    private void btnGestionarRobosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarRobosMouseExited
        botonDespresionado(btnGestionarRobos);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarRobosMouseExited

    private void btnGestionarRobosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarRobosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarRobosActionPerformed

    private void btnCerrarSesionSeguridadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionSeguridadMouseEntered
        botonPresionado(btnCerrarSesionSeguridad);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionSeguridadMouseEntered

    private void btnCerrarSesionSeguridadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionSeguridadMouseExited
        botonDespresionado(btnCerrarSesionSeguridad);     // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionSeguridadMouseExited

    private void btnCerrarSesionSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionSeguridadActionPerformed

        Login login = new Login();

        login.setLocationRelativeTo(null);
        login.setResizable(false);
        login.setVisible(true);

        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionSeguridadActionPerformed

    private void btnGestionarIncidentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarIncidentesMouseEntered
        botonPresionado(btnGestionarIncidentes);// TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarIncidentesMouseEntered

    private void btnGestionarIncidentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarIncidentesMouseExited
        botonDespresionado(btnGestionarIncidentes);// TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarIncidentesMouseExited

    private void btnGestionarIncidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarIncidentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarIncidentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeguridadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeguridadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeguridadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeguridadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeguridadFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesionSeguridad;
    private javax.swing.JButton btnGestionarAreaSeguridad;
    private javax.swing.JButton btnGestionarIncidentes;
    private javax.swing.JButton btnGestionarRobos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane panelGeneralSeguridad;
    private javax.swing.JPanel panelGestionarAreaSeguridad;
    private javax.swing.JPanel panelGestionarIncidentes;
    private javax.swing.JPanel panelGestionarRobos;
    // End of variables declaration//GEN-END:variables
}
