/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.seguridad.areas;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logica.seguridad.areas.ListaAreas;
import ui.utilidades.EliminadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class GestionarArea extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    String[] columnas = {"Identificación", "Fecha", "Nombre área", "Ubicación área", "Tamano área", "Encargado", "Cedula encargado", "Hora inicio", "Hora fin", "Piso área", "Finalizado?"};

    /**
     * Creates new form GestionarArea
     */
    public GestionarArea() {
        initComponents();

        modelo.setColumnIdentifiers(columnas);

        tblUnicaArea.setRowHeight(40);

        tblUnicaArea.setModel(modelo);

        escalarLargoTablas(columnas.length, tblUnicaArea);
    }

    public void escalarLargoTablas(int tamanoColumnas, JTable tabla) {
        for (int i = 0; i < tamanoColumnas; i++) {
            tabla.getColumnModel().getColumn(i).setPreferredWidth(200);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnSalirVentanaGestionArea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnicaArea = new javax.swing.JTable();
        lbNombreEncargadoArea = new javax.swing.JLabel();
        txtfBuscarArea = new javax.swing.JTextField();
        btnBuscarAreaID = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnEliminarArea = new javax.swing.JButton();
        btnFinalizarTareaDesdeLimp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1120, 550));
        setMinimumSize(new java.awt.Dimension(1120, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMinimumSize(new java.awt.Dimension(1120, 90));
        jPanel6.setPreferredSize(new java.awt.Dimension(1120, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Área");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        btnSalirVentanaGestionArea.setBackground(new java.awt.Color(127, 156, 90));
        btnSalirVentanaGestionArea.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnSalirVentanaGestionArea.setForeground(new java.awt.Color(0, 0, 0));
        btnSalirVentanaGestionArea.setText("X");
        btnSalirVentanaGestionArea.setBorder(null);
        btnSalirVentanaGestionArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVentanaGestionAreaActionPerformed(evt);
            }
        });
        jPanel6.add(btnSalirVentanaGestionArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 90));

        tblUnicaArea.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tblUnicaArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUnicaArea.setAutoResizeMode(0);
        jScrollPane1.setViewportView(tblUnicaArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 1090, 80));

        lbNombreEncargadoArea.setBackground(new java.awt.Color(0, 0, 0));
        lbNombreEncargadoArea.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18)); // NOI18N
        lbNombreEncargadoArea.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbNombreEncargadoArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 280, 30));

        txtfBuscarArea.setBackground(new java.awt.Color(153, 195, 84));
        txtfBuscarArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfBuscarArea.setForeground(new java.awt.Color(0, 0, 0));
        txtfBuscarArea.setBorder(null);
        jPanel1.add(txtfBuscarArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 350, 45));

        btnBuscarAreaID.setBackground(new java.awt.Color(127, 156, 90));
        btnBuscarAreaID.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnBuscarAreaID.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarAreaID.setText("Buscar ronda");
        btnBuscarAreaID.setBorder(null);
        btnBuscarAreaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAreaIDActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarAreaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 45));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Número de identificación ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Encargado");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        btnEliminarArea.setBackground(new java.awt.Color(127, 156, 90));
        btnEliminarArea.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEliminarArea.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarArea.setText("Eliminar ronda");
        btnEliminarArea.setBorder(null);
        btnEliminarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAreaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 130, 45));

        btnFinalizarTareaDesdeLimp.setBackground(new java.awt.Color(127, 156, 90));
        btnFinalizarTareaDesdeLimp.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnFinalizarTareaDesdeLimp.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizarTareaDesdeLimp.setText("Finalizar ronda");
        btnFinalizarTareaDesdeLimp.setBorder(null);
        btnFinalizarTareaDesdeLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarTareaDesdeLimpActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizarTareaDesdeLimp, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 130, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirVentanaGestionAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVentanaGestionAreaActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirVentanaGestionAreaActionPerformed

    private void btnBuscarAreaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAreaIDActionPerformed

        int ID = Integer.parseInt(txtfBuscarArea.getText());

        Object[] ob = {ID, ListaAreas.getAreasCentroComercial().get(ID).getFecha(), ListaAreas.getAreasCentroComercial().get(ID).getNombreArea(), ListaAreas.getAreasCentroComercial().get(ID).getUbicacionArea(), ListaAreas.getAreasCentroComercial().get(ID).getTamanoArea(), ListaAreas.getAreasCentroComercial().get(ID).getNombreEncargadoArea(), ListaAreas.getAreasCentroComercial().get(ID).getCedulaEncargadoArea(), ListaAreas.getAreasCentroComercial().get(ID).getHoraInicioEncargadoArea(), ListaAreas.getAreasCentroComercial().get(ID).getHoraFinEncargadoArea(), ListaAreas.getAreasCentroComercial().get(ID).getPisoArea(), ListaAreas.getAreasCentroComercial().get(ID).getTerminado()};

        lbNombreEncargadoArea.setText(ListaAreas.getAreasCentroComercial().get(ID).getNombreEncargadoArea());

        modelo.addRow(ob);
        escalarLargoTablas(columnas.length, tblUnicaArea);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarAreaIDActionPerformed

    private void btnEliminarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAreaActionPerformed
        int ID = Integer.parseInt(txtfBuscarArea.getText());

        ListaAreas.getAreasCentroComercial().remove(ID);

        this.dispose();
        EliminadoExitosamente elim = new EliminadoExitosamente();

        elim.setLocationRelativeTo(null);
        elim.setResizable(false);
        elim.setVisible(true);
    }//GEN-LAST:event_btnEliminarAreaActionPerformed

    private void btnFinalizarTareaDesdeLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarTareaDesdeLimpActionPerformed

        int ID = Integer.parseInt(txtfBuscarArea.getText());

        ListaAreas.getAreasCentroComercial().get(ID).setTerminado("Si");

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarTareaDesdeLimpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAreaID;
    private javax.swing.JButton btnEliminarArea;
    private javax.swing.JButton btnFinalizarTareaDesdeLimp;
    private javax.swing.JButton btnSalirVentanaGestionArea;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNombreEncargadoArea;
    private javax.swing.JTable tblUnicaArea;
    private javax.swing.JTextField txtfBuscarArea;
    // End of variables declaration//GEN-END:variables
}
