/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.serviciosGenerales.limpiezas;

import javax.swing.JLabel;
import javax.swing.JTextField;
import logica.serviciosGenerales.tareas.ListaTareas;
import ui.utilidades.EditadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class EditarLimpieza extends javax.swing.JFrame {

    public JLabel getLbNumeroIdentificacionLimpieza() {
        return lbNumeroIdentificacionLimpieza;
    }

    public void setLbNumeroIdentificacionLimpieza(JLabel lbNumeroIdentificacionLimpieza) {
        this.lbNumeroIdentificacionLimpieza = lbNumeroIdentificacionLimpieza;
    }

    private int IDeditar;

    public int getIDeditar() {
        return IDeditar;
    }

    public void setIDeditar(int IDeditar) {
        this.IDeditar = IDeditar;
    }

    public JTextField getTxtfNUEVOAreaTarea() {
        return txtfNUEVOAreaTarea;
    }

    public void setTxtfNUEVOAreaTarea(JTextField txtfNUEVOAreaTarea) {
        this.txtfNUEVOAreaTarea = txtfNUEVOAreaTarea;
    }

    public JTextField getTxtfNUEVOdescripcionTarea() {
        return txtfNUEVOdescripcionTarea;
    }

    public void setTxtfNUEVOdescripcionTarea(JTextField txtfNUEVOdescripcionTarea) {
        this.txtfNUEVOdescripcionTarea = txtfNUEVOdescripcionTarea;
    }

    public JTextField getTxtfNUEVOestaFinalizada() {
        return txtfNUEVOestaFinalizada;
    }

    public void setTxtfNUEVOestaFinalizada(JTextField txtfNUEVOestaFinalizada) {
        this.txtfNUEVOestaFinalizada = txtfNUEVOestaFinalizada;
    }

    public JTextField getTxtfNUEVOnombreTarea() {
        return txtfNUEVOnombreTarea;
    }

    public void setTxtfNUEVOnombreTarea(JTextField txtfNUEVOnombreTarea) {
        this.txtfNUEVOnombreTarea = txtfNUEVOnombreTarea;
    }

    public JTextField getTxtfNUEVOpersonaEncargada() {
        return txtfNUEVOpersonaEncargada;
    }

    public void setTxtfNUEVOpersonaEncargada(JTextField txtfNUEVOpersonaEncargada) {
        this.txtfNUEVOpersonaEncargada = txtfNUEVOpersonaEncargada;
    }

    /**
     * Creates new form EditarLimpieza
     */
    public EditarLimpieza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolverInicioEditarLimpieza = new javax.swing.JButton();
        lbNumeroIdentificacionLimpieza = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfNUEVOnombreTarea = new javax.swing.JTextField();
        txtfNUEVOpersonaEncargada = new javax.swing.JTextField();
        txtfNUEVOestaFinalizada = new javax.swing.JTextField();
        txtfNUEVOdescripcionTarea = new javax.swing.JTextField();
        txtfNUEVOAreaTarea = new javax.swing.JTextField();
        btnEditarLimpiezaEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(990, 880));
        setMinimumSize(new java.awt.Dimension(990, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel6.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel6.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Editar limpieza");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btnVolverInicioEditarLimpieza.setBackground(new java.awt.Color(127, 156, 90));
        btnVolverInicioEditarLimpieza.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolverInicioEditarLimpieza.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicioEditarLimpieza.setText("X");
        btnVolverInicioEditarLimpieza.setBorder(null);
        btnVolverInicioEditarLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioEditarLimpiezaActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolverInicioEditarLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        lbNumeroIdentificacionLimpieza.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbNumeroIdentificacionLimpieza.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbNumeroIdentificacionLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 300, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Número de identificación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre de la tarea");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Área de la tarea");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Persona encargada");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Finalizada? (Si/No)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descripción de la tarea");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, 30));

        txtfNUEVOnombreTarea.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOnombreTarea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOnombreTarea.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOnombreTarea.setText("Pendiente");
        txtfNUEVOnombreTarea.setBorder(null);
        jPanel1.add(txtfNUEVOnombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 350, 45));

        txtfNUEVOpersonaEncargada.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOpersonaEncargada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOpersonaEncargada.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOpersonaEncargada.setText("Pendiente");
        txtfNUEVOpersonaEncargada.setBorder(null);
        jPanel1.add(txtfNUEVOpersonaEncargada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 350, 45));

        txtfNUEVOestaFinalizada.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOestaFinalizada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOestaFinalizada.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOestaFinalizada.setText("Pendiente");
        txtfNUEVOestaFinalizada.setBorder(null);
        jPanel1.add(txtfNUEVOestaFinalizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 350, 45));

        txtfNUEVOdescripcionTarea.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOdescripcionTarea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOdescripcionTarea.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOdescripcionTarea.setText("Pendiente");
        txtfNUEVOdescripcionTarea.setBorder(null);
        jPanel1.add(txtfNUEVOdescripcionTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 350, 45));

        txtfNUEVOAreaTarea.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOAreaTarea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOAreaTarea.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOAreaTarea.setText("Pendiente");
        txtfNUEVOAreaTarea.setBorder(null);
        jPanel1.add(txtfNUEVOAreaTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 350, 45));

        btnEditarLimpiezaEnviar.setBackground(new java.awt.Color(127, 156, 90));
        btnEditarLimpiezaEnviar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEditarLimpiezaEnviar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarLimpiezaEnviar.setText("Editar limpieza");
        btnEditarLimpiezaEnviar.setBorder(null);
        btnEditarLimpiezaEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLimpiezaEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarLimpiezaEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioEditarLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioEditarLimpiezaActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioEditarLimpiezaActionPerformed

    private void btnEditarLimpiezaEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLimpiezaEnviarActionPerformed

        
        ListaTareas.getTareasCentroComercial().get(IDeditar).setNombreTarea(txtfNUEVOnombreTarea.getText());
        
        ListaTareas.getTareasCentroComercial().get(IDeditar).setPersonaEncargada(txtfNUEVOpersonaEncargada.getText());
        
        ListaTareas.getTareasCentroComercial().get(IDeditar).setRealizadaTarea(txtfNUEVOestaFinalizada.getText());
        
        ListaTareas.getTareasCentroComercial().get(IDeditar).setDescripcionTarea(txtfNUEVOdescripcionTarea.getText());
        
        ListaTareas.getTareasCentroComercial().get(IDeditar).setAreaTarea(txtfNUEVOAreaTarea.getText());
        
        EditadoExitosamente editado = new EditadoExitosamente();

        this.dispose();

        editado.setLocationRelativeTo(null);
        editado.setResizable(false);
        editado.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarLimpiezaEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarLimpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarLimpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarLimpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarLimpieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarLimpieza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarLimpiezaEnviar;
    private javax.swing.JButton btnVolverInicioEditarLimpieza;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbNumeroIdentificacionLimpieza;
    private javax.swing.JTextField txtfNUEVOAreaTarea;
    private javax.swing.JTextField txtfNUEVOdescripcionTarea;
    private javax.swing.JTextField txtfNUEVOestaFinalizada;
    private javax.swing.JTextField txtfNUEVOnombreTarea;
    private javax.swing.JTextField txtfNUEVOpersonaEncargada;
    // End of variables declaration//GEN-END:variables
}
