/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.login;

import java.awt.Color;
import logica.administrativos.Administrativos;
import logica.contador.Contador;
import ui.administrativos.AdministrativosFrame;
import ui.contador.ContadorFrame;

/**
 *
 * @author Nicolas
 */
public class Login extends javax.swing.JFrame {

    Color colorBotonPresionado = new Color(153, 195, 84);

    /**
     * Creates new form InicioSesion
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfInicioSesionUsuario = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        pssdfClaveInicioSesion = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Inicio de sesión");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Clave");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        txtfInicioSesionUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtfInicioSesionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfInicioSesionUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtfInicioSesionUsuario.setText("Ingrese su nombre de usuario");
        txtfInicioSesionUsuario.setBorder(null);
        txtfInicioSesionUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtfInicioSesionUsuarioMouseClicked(evt);
            }
        });
        txtfInicioSesionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfInicioSesionUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtfInicioSesionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 412, 45));

        btnIniciarSesion.setBackground(new java.awt.Color(153, 195, 84));
        btnIniciarSesion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion.setText("ENTRAR");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 160, 50));

        pssdfClaveInicioSesion.setBackground(new java.awt.Color(255, 255, 255));
        pssdfClaveInicioSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pssdfClaveInicioSesion.setForeground(new java.awt.Color(204, 204, 204));
        pssdfClaveInicioSesion.setText("Ingrese su clave");
        pssdfClaveInicioSesion.setBorder(null);
        pssdfClaveInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pssdfClaveInicioSesionMouseClicked(evt);
            }
        });
        pssdfClaveInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssdfClaveInicioSesionActionPerformed(evt);
            }
        });
        jPanel1.add(pssdfClaveInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 412, 45));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 400, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 400, 10));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("X");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 590, 720));

        jPanel2.setBackground(new java.awt.Color(153, 195, 84));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfInicioSesionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfInicioSesionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfInicioSesionUsuarioActionPerformed

    private void pssdfClaveInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssdfClaveInicioSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pssdfClaveInicioSesionActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        AdministrativosFrame admin = new AdministrativosFrame();
        ContadorFrame contador = new ContadorFrame();

        LoginNoAceptado noAceptado = new LoginNoAceptado();

        String usuarioInput = txtfInicioSesionUsuario.getText();
        String claveInput = pssdfClaveInicioSesion.getText();

        if (usuarioInput.equals(Administrativos.getUsuarioAdministrativo()) && claveInput.equals(Administrativos.getClaveAdministrativo())) {
            admin.setLocationRelativeTo(null);
            admin.setResizable(false);
            admin.setVisible(true);
            
            this.dispose();
        } else if (usuarioInput.equals(Contador.getUsuarioContador()) && claveInput.equals(Contador.getClaveContador())) {

            contador.setLocationRelativeTo(null);
            contador.setResizable(false);
            contador.setVisible(true);
            this.dispose();

        } else {

            noAceptado.setLocationRelativeTo(null);
            noAceptado.setResizable(false);
            noAceptado.setVisible(true);
            this.dispose();

        }


        //
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtfInicioSesionUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfInicioSesionUsuarioMouseClicked
        txtfInicioSesionUsuario.setText("");
        txtfInicioSesionUsuario.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_txtfInicioSesionUsuarioMouseClicked

    private void pssdfClaveInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pssdfClaveInicioSesionMouseClicked
        // TODO add your handling code here:

        pssdfClaveInicioSesion.setText("");
        pssdfClaveInicioSesion.setForeground(Color.BLACK);
    }//GEN-LAST:event_pssdfClaveInicioSesionMouseClicked

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pssdfClaveInicioSesion;
    private javax.swing.JTextField txtfInicioSesionUsuario;
    // End of variables declaration//GEN-END:variables
}
