/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.contador.gastos;

import javax.swing.JLabel;
import javax.swing.JTextField;
import logica.contador.gastos.ListaGastos;
import ui.utilidades.EditadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class EditarGasto extends javax.swing.JFrame {

    private int IDentificador;

    public int getIDentificador() {
        return IDentificador;
    }

    public void setIDentificador(int IDentificador) {
        this.IDentificador = IDentificador;
    }

    /**
     * Creates new form EditarGasto
     */
    public EditarGasto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolverInicioEditarGasto = new javax.swing.JButton();
        lbIdentificadorGasto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtfNUEVOcantidadMon = new javax.swing.JTextField();
        txtfNUEVOfechaGasto = new javax.swing.JTextField();
        txtfNUEVOconcepto = new javax.swing.JTextField();
        txtfNUEVOproveedor = new javax.swing.JTextField();
        txtfNUEVOnumeroRecibo = new javax.swing.JTextField();
        txtfNUEVOmetodoPago = new javax.swing.JTextField();
        txtfNUEVOareaDestino = new javax.swing.JTextField();
        txtfNUEVOcategoria = new javax.swing.JTextField();
        btnEditarGasto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(983, 880));
        setMinimumSize(new java.awt.Dimension(983, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel1.setName("a"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel6.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel6.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Editar gasto");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        btnVolverInicioEditarGasto.setBackground(new java.awt.Color(127, 156, 90));
        btnVolverInicioEditarGasto.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolverInicioEditarGasto.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicioEditarGasto.setText("X");
        btnVolverInicioEditarGasto.setBorder(null);
        btnVolverInicioEditarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioEditarGastoActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolverInicioEditarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        lbIdentificadorGasto.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbIdentificadorGasto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbIdentificadorGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 210, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Identificador");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad monetaria");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha del gasto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Concepto ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Proveedor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, -1, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Número recibo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Categoría");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Área destino");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Método de pago");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, -1, 30));

        txtfNUEVOcantidadMon.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOcantidadMon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOcantidadMon.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOcantidadMon.setText("0");
        txtfNUEVOcantidadMon.setBorder(null);
        jPanel1.add(txtfNUEVOcantidadMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 350, 45));

        txtfNUEVOfechaGasto.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOfechaGasto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOfechaGasto.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOfechaGasto.setText("0");
        txtfNUEVOfechaGasto.setBorder(null);
        jPanel1.add(txtfNUEVOfechaGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 350, 45));

        txtfNUEVOconcepto.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOconcepto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOconcepto.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOconcepto.setText("0");
        txtfNUEVOconcepto.setBorder(null);
        jPanel1.add(txtfNUEVOconcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 350, 45));

        txtfNUEVOproveedor.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOproveedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOproveedor.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOproveedor.setText("0");
        txtfNUEVOproveedor.setBorder(null);
        jPanel1.add(txtfNUEVOproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 350, 45));

        txtfNUEVOnumeroRecibo.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOnumeroRecibo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOnumeroRecibo.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOnumeroRecibo.setText("0");
        txtfNUEVOnumeroRecibo.setBorder(null);
        jPanel1.add(txtfNUEVOnumeroRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 350, 45));

        txtfNUEVOmetodoPago.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOmetodoPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOmetodoPago.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOmetodoPago.setText("0");
        txtfNUEVOmetodoPago.setBorder(null);
        jPanel1.add(txtfNUEVOmetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 350, 45));

        txtfNUEVOareaDestino.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOareaDestino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOareaDestino.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOareaDestino.setText("0");
        txtfNUEVOareaDestino.setBorder(null);
        jPanel1.add(txtfNUEVOareaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 350, 45));

        txtfNUEVOcategoria.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOcategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOcategoria.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOcategoria.setText("0");
        txtfNUEVOcategoria.setBorder(null);
        jPanel1.add(txtfNUEVOcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 350, 45));

        btnEditarGasto.setBackground(new java.awt.Color(127, 156, 90));
        btnEditarGasto.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEditarGasto.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarGasto.setText("Editar gasto");
        btnEditarGasto.setBorder(null);
        btnEditarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGastoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioEditarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioEditarGastoActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioEditarGastoActionPerformed

    public JLabel getLbIdentificadorGasto() {
        return lbIdentificadorGasto;
    }

    public void setLbIdentificadorGasto(JLabel lbIdentificadorGasto) {
        this.lbIdentificadorGasto = lbIdentificadorGasto;
    }

    public JTextField getTxtfNUEVOareaDestino() {
        return txtfNUEVOareaDestino;
    }

    public void setTxtfNUEVOareaDestino(JTextField txtfNUEVOareaDestino) {
        this.txtfNUEVOareaDestino = txtfNUEVOareaDestino;
    }

    public JTextField getTxtfNUEVOcantidadMon() {
        return txtfNUEVOcantidadMon;
    }

    public void setTxtfNUEVOcantidadMon(JTextField txtfNUEVOcantidadMon) {
        this.txtfNUEVOcantidadMon = txtfNUEVOcantidadMon;
    }

    public JTextField getTxtfNUEVOcategoria() {
        return txtfNUEVOcategoria;
    }

    public void setTxtfNUEVOcategoria(JTextField txtfNUEVOcategoria) {
        this.txtfNUEVOcategoria = txtfNUEVOcategoria;
    }

    public JTextField getTxtfNUEVOconcepto() {
        return txtfNUEVOconcepto;
    }

    public void setTxtfNUEVOconcepto(JTextField txtfNUEVOconcepto) {
        this.txtfNUEVOconcepto = txtfNUEVOconcepto;
    }

    public JTextField getTxtfNUEVOfechaGasto() {
        return txtfNUEVOfechaGasto;
    }

    public void setTxtfNUEVOfechaGasto(JTextField txtfNUEVOfechaGasto) {
        this.txtfNUEVOfechaGasto = txtfNUEVOfechaGasto;
    }

    public JTextField getTxtfNUEVOmetodoPago() {
        return txtfNUEVOmetodoPago;
    }

    public void setTxtfNUEVOmetodoPago(JTextField txtfNUEVOmetodoPago) {
        this.txtfNUEVOmetodoPago = txtfNUEVOmetodoPago;
    }

    public JTextField getTxtfNUEVOnumeroRecibo() {
        return txtfNUEVOnumeroRecibo;
    }

    public void setTxtfNUEVOnumeroRecibo(JTextField txtfNUEVOnumeroRecibo) {
        this.txtfNUEVOnumeroRecibo = txtfNUEVOnumeroRecibo;
    }

    public JTextField getTxtfNUEVOproveedor() {
        return txtfNUEVOproveedor;
    }

    public void setTxtfNUEVOproveedor(JTextField txtfNUEVOproveedor) {
        this.txtfNUEVOproveedor = txtfNUEVOproveedor;
    }

    private void btnEditarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGastoActionPerformed

        ListaGastos.getGastosCentroComercial().get(IDentificador).setCantidadMonetariaGasto(Integer.parseInt(txtfNUEVOcantidadMon.getText()));
        ListaGastos.getGastosCentroComercial().get(IDentificador).setFechaGasto(txtfNUEVOfechaGasto.getText());
        ListaGastos.getGastosCentroComercial().get(IDentificador).setConceptoGasto(txtfNUEVOconcepto.getText());
        ListaGastos.getGastosCentroComercial().get(IDentificador).setProveedorGasto(txtfNUEVOproveedor.getText());
        ListaGastos.getGastosCentroComercial().get(IDentificador).setNumeroReciboGasto(Integer.parseInt(txtfNUEVOnumeroRecibo.getText()));
        ListaGastos.getGastosCentroComercial().get(IDentificador).setCategoriaGasto(txtfNUEVOcategoria.getText());
        ListaGastos.getGastosCentroComercial().get(IDentificador).setAreaDestinoGasto(txtfNUEVOareaDestino.getText());
        ListaGastos.getGastosCentroComercial().get(IDentificador).setMetodoPagoGasto(txtfNUEVOmetodoPago.getText());

        EditadoExitosamente editado = new EditadoExitosamente();

        this.dispose();

        editado.setLocationRelativeTo(null);
        editado.setResizable(false);
        editado.setVisible(true);
    }//GEN-LAST:event_btnEditarGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarGasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarGasto;
    private javax.swing.JButton btnVolverInicioEditarGasto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbIdentificadorGasto;
    private javax.swing.JTextField txtfNUEVOareaDestino;
    private javax.swing.JTextField txtfNUEVOcantidadMon;
    private javax.swing.JTextField txtfNUEVOcategoria;
    private javax.swing.JTextField txtfNUEVOconcepto;
    private javax.swing.JTextField txtfNUEVOfechaGasto;
    private javax.swing.JTextField txtfNUEVOmetodoPago;
    private javax.swing.JTextField txtfNUEVOnumeroRecibo;
    private javax.swing.JTextField txtfNUEVOproveedor;
    // End of variables declaration//GEN-END:variables
}
