/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.administrativos.contratosLocal;

import javax.swing.JLabel;
import javax.swing.JTextField;
import logica.administrativos.contratosLocales.ListaContratosLocales;
import ui.utilidades.EditadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class EditarContratoLocal extends javax.swing.JFrame {

    private int IDeditar;

    public int getIDeditar() {
        return IDeditar;
    }

    public void setIDeditar(int IDeditar) {
        this.IDeditar = IDeditar;
    }

    public JLabel getLbIdentificacionContratoLocal() {
        return lbIdentificacionContratoLocal;
    }

    public void setLbIdentificacionContratoLocal(JLabel lbIdentificacionContratoLocal) {
        this.lbIdentificacionContratoLocal = lbIdentificacionContratoLocal;
    }

    public JTextField getTxtfNUEVOCedulaArrendatario() {
        return txtfNUEVOCedulaArrendatario;
    }

    public void setTxtfNUEVOCedulaArrendatario(JTextField txtfNUEVOCedulaArrendatario) {
        this.txtfNUEVOCedulaArrendatario = txtfNUEVOCedulaArrendatario;
    }

    public JTextField getTxtfNUEVOCondicionesRenovacion() {
        return txtfNUEVOCondicionesRenovacion;
    }

    public void setTxtfNUEVOCondicionesRenovacion(JTextField txtfNUEVOCondicionesRenovacion) {
        this.txtfNUEVOCondicionesRenovacion = txtfNUEVOCondicionesRenovacion;
    }

    public JTextField getTxtfNUEVODEscripcionContrato() {
        return txtfNUEVODEscripcionContrato;
    }

    public void setTxtfNUEVODEscripcionContrato(JTextField txtfNUEVODEscripcionContrato) {
        this.txtfNUEVODEscripcionContrato = txtfNUEVODEscripcionContrato;
    }

    public JTextField getTxtfNUEVODuracionContrato() {
        return txtfNUEVODuracionContrato;
    }

    public void setTxtfNUEVODuracionContrato(JTextField txtfNUEVODuracionContrato) {
        this.txtfNUEVODuracionContrato = txtfNUEVODuracionContrato;
    }

    public JTextField getTxtfNUEVOMontoMensual() {
        return txtfNUEVOMontoMensual;
    }

    public void setTxtfNUEVOMontoMensual(JTextField txtfNUEVOMontoMensual) {
        this.txtfNUEVOMontoMensual = txtfNUEVOMontoMensual;
    }

    public JTextField getTxtfNUEVONombreLocal() {
        return txtfNUEVONombreLocal;
    }

    public void setTxtfNUEVONombreLocal(JTextField txtfNUEVONombreLocal) {
        this.txtfNUEVONombreLocal = txtfNUEVONombreLocal;
    }

    public JTextField getTxtfNUEVOPlazosPago() {
        return txtfNUEVOPlazosPago;
    }

    public void setTxtfNUEVOPlazosPago(JTextField txtfNUEVOPlazosPago) {
        this.txtfNUEVOPlazosPago = txtfNUEVOPlazosPago;
    }

    public JTextField getTxtfNUEVOSegurosLocal() {
        return txtfNUEVOSegurosLocal;
    }

    public void setTxtfNUEVOSegurosLocal(JTextField txtfNUEVOSegurosLocal) {
        this.txtfNUEVOSegurosLocal = txtfNUEVOSegurosLocal;
    }

    public JTextField getTxtfNUEVOUsoLocal() {
        return txtfNUEVOUsoLocal;
    }

    public void setTxtfNUEVOUsoLocal(JTextField txtfNUEVOUsoLocal) {
        this.txtfNUEVOUsoLocal = txtfNUEVOUsoLocal;
    }

    public JTextField getTxtfNUEVOnombreArrendatario() {
        return txtfNUEVOnombreArrendatario;
    }

    public void setTxtfNUEVOnombreArrendatario(JTextField txtfNUEVOnombreArrendatario) {
        this.txtfNUEVOnombreArrendatario = txtfNUEVOnombreArrendatario;
    }

    /**
     * Creates new form EditarContratoLocal
     */
    public EditarContratoLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolverInicioEditarCLocal = new javax.swing.JButton();
        lbIdentificacionContratoLocal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfNUEVOSegurosLocal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtfNUEVOnombreArrendatario = new javax.swing.JTextField();
        txtfNUEVOCedulaArrendatario = new javax.swing.JTextField();
        txtfNUEVODEscripcionContrato = new javax.swing.JTextField();
        txtfNUEVODuracionContrato = new javax.swing.JTextField();
        txtfNUEVOCondicionesRenovacion = new javax.swing.JTextField();
        txtfNUEVOMontoMensual = new javax.swing.JTextField();
        txtfNUEVOPlazosPago = new javax.swing.JTextField();
        txtfNUEVOUsoLocal = new javax.swing.JTextField();
        txtfNUEVONombreLocal = new javax.swing.JTextField();
        btnEditarContratoLocal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(990, 880));
        setMinimumSize(new java.awt.Dimension(990, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel6.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel6.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Editar contrato local");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        btnVolverInicioEditarCLocal.setBackground(new java.awt.Color(127, 156, 90));
        btnVolverInicioEditarCLocal.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolverInicioEditarCLocal.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicioEditarCLocal.setText("X");
        btnVolverInicioEditarCLocal.setBorder(null);
        btnVolverInicioEditarCLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioEditarCLocalActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolverInicioEditarCLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        lbIdentificacionContratoLocal.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbIdentificacionContratoLocal.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbIdentificacionContratoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 240, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre arrendatario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 30));

        txtfNUEVOSegurosLocal.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOSegurosLocal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOSegurosLocal.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOSegurosLocal.setText("Pendiente");
        txtfNUEVOSegurosLocal.setBorder(null);
        jPanel1.add(txtfNUEVOSegurosLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 350, 45));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cedula arrendatario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descripción del contrato");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Duración del contrato");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Condiciones de renovación");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, -1, 30));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Seguros");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, -1, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nombre del local");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Uso del local");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Plazos de pago");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Monto mensual");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Número de identificación");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 30));

        txtfNUEVOnombreArrendatario.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOnombreArrendatario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOnombreArrendatario.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOnombreArrendatario.setText("Pendiente");
        txtfNUEVOnombreArrendatario.setBorder(null);
        jPanel1.add(txtfNUEVOnombreArrendatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 350, 45));

        txtfNUEVOCedulaArrendatario.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOCedulaArrendatario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOCedulaArrendatario.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOCedulaArrendatario.setText("Pendiente");
        txtfNUEVOCedulaArrendatario.setBorder(null);
        jPanel1.add(txtfNUEVOCedulaArrendatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 350, 45));

        txtfNUEVODEscripcionContrato.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVODEscripcionContrato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVODEscripcionContrato.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVODEscripcionContrato.setText("Pendiente");
        txtfNUEVODEscripcionContrato.setBorder(null);
        jPanel1.add(txtfNUEVODEscripcionContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 350, 45));

        txtfNUEVODuracionContrato.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVODuracionContrato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVODuracionContrato.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVODuracionContrato.setText("Pendiente");
        txtfNUEVODuracionContrato.setBorder(null);
        jPanel1.add(txtfNUEVODuracionContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 350, 45));

        txtfNUEVOCondicionesRenovacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOCondicionesRenovacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOCondicionesRenovacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOCondicionesRenovacion.setText("Pendiente");
        txtfNUEVOCondicionesRenovacion.setBorder(null);
        jPanel1.add(txtfNUEVOCondicionesRenovacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 720, 350, 45));

        txtfNUEVOMontoMensual.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOMontoMensual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOMontoMensual.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOMontoMensual.setText("0");
        txtfNUEVOMontoMensual.setBorder(null);
        jPanel1.add(txtfNUEVOMontoMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 350, 45));

        txtfNUEVOPlazosPago.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOPlazosPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOPlazosPago.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOPlazosPago.setText("Pendiente");
        txtfNUEVOPlazosPago.setBorder(null);
        jPanel1.add(txtfNUEVOPlazosPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 350, 45));

        txtfNUEVOUsoLocal.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOUsoLocal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOUsoLocal.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOUsoLocal.setText("Pendiente");
        txtfNUEVOUsoLocal.setBorder(null);
        jPanel1.add(txtfNUEVOUsoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 350, 45));

        txtfNUEVONombreLocal.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVONombreLocal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVONombreLocal.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVONombreLocal.setText("Pendiente");
        txtfNUEVONombreLocal.setBorder(null);
        jPanel1.add(txtfNUEVONombreLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 350, 45));

        btnEditarContratoLocal.setBackground(new java.awt.Color(127, 156, 90));
        btnEditarContratoLocal.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEditarContratoLocal.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarContratoLocal.setText("Editar contrato");
        btnEditarContratoLocal.setBorder(null);
        btnEditarContratoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContratoLocalActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarContratoLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 800, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioEditarCLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioEditarCLocalActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioEditarCLocalActionPerformed

    private void btnEditarContratoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContratoLocalActionPerformed

        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setNombreArrendatarioContrato(txtfNUEVOnombreArrendatario.getText());

        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setCedulaArrendatario(txtfNUEVOCedulaArrendatario.getText());
        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setDescripcionContrato(txtfNUEVODEscripcionContrato.getText());
        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setDuracionContrato(txtfNUEVODuracionContrato.getText());
        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setCondicionesDeRenovacionContrato(txtfNUEVOCondicionesRenovacion.getText());
        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setMontoMensualContrato(Integer.parseInt(txtfNUEVOMontoMensual.getText()));
        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setPlazosDePagoContrato(txtfNUEVOPlazosPago.getText());
        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setUsoDelLocalContrato(txtfNUEVOUsoLocal.getText());
        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setNombreLocalContrato(txtfNUEVONombreLocal.getText());
        ListaContratosLocales.getContratosCentroComercial().get(IDeditar).setSeguros(txtfNUEVOSegurosLocal.getText());

        EditadoExitosamente editado = new EditadoExitosamente();

        this.dispose();

        editado.setLocationRelativeTo(null);
        editado.setResizable(false);
        editado.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarContratoLocalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarContratoLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarContratoLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarContratoLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarContratoLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarContratoLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarContratoLocal;
    private javax.swing.JButton btnVolverInicioEditarCLocal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbIdentificacionContratoLocal;
    private javax.swing.JTextField txtfNUEVOCedulaArrendatario;
    private javax.swing.JTextField txtfNUEVOCondicionesRenovacion;
    private javax.swing.JTextField txtfNUEVODEscripcionContrato;
    private javax.swing.JTextField txtfNUEVODuracionContrato;
    private javax.swing.JTextField txtfNUEVOMontoMensual;
    private javax.swing.JTextField txtfNUEVONombreLocal;
    private javax.swing.JTextField txtfNUEVOPlazosPago;
    private javax.swing.JTextField txtfNUEVOSegurosLocal;
    private javax.swing.JTextField txtfNUEVOUsoLocal;
    private javax.swing.JTextField txtfNUEVOnombreArrendatario;
    // End of variables declaration//GEN-END:variables
}
