/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.contador.ingresos;

import javax.swing.JLabel;
import javax.swing.JTextField;
import logica.contador.ingresos.ListaIngresos;
import ui.utilidades.EditadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class EditarIngreso extends javax.swing.JFrame {

    private int Identificador;

    public int getIdentificador() {
        return Identificador;
    }

    public void setIdentificador(int Identificador) {
        this.Identificador = Identificador;
    }

    /**
     * Creates new form EditarIngreso
     */
    public EditarIngreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolverInicioINgresoEditar = new javax.swing.JButton();
        lbIDingreso = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfNUEVOareaOrigenIngreso = new javax.swing.JTextField();
        txtfNUEVOcantMonetaria = new javax.swing.JTextField();
        txtfNUEVOfechaIngreso = new javax.swing.JTextField();
        txtfNUEVOorigenIngreso = new javax.swing.JTextField();
        txtfNUEVOtipoIngreso = new javax.swing.JTextField();
        txtfNUEVOmetodoPagoIngreso = new javax.swing.JTextField();
        btnEditarIngreso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(983, 880));
        setMinimumSize(new java.awt.Dimension(983, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel1.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Editar ingreso");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        btnVolverInicioINgresoEditar.setBackground(new java.awt.Color(127, 156, 90));
        btnVolverInicioINgresoEditar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolverInicioINgresoEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicioINgresoEditar.setText("X");
        btnVolverInicioINgresoEditar.setBorder(null);
        btnVolverInicioINgresoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioINgresoEditarActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolverInicioINgresoEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        lbIDingreso.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lbIDingreso.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbIDingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 220, 30));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Identificador");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cantidad monetaria");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha de ingreso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Origen de ingreso");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Área de origen");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Método de pago");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tipo de ingreso");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, 30));

        txtfNUEVOareaOrigenIngreso.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOareaOrigenIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOareaOrigenIngreso.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOareaOrigenIngreso.setText("0");
        txtfNUEVOareaOrigenIngreso.setBorder(null);
        jPanel1.add(txtfNUEVOareaOrigenIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 350, 45));

        txtfNUEVOcantMonetaria.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOcantMonetaria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOcantMonetaria.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOcantMonetaria.setText("0");
        txtfNUEVOcantMonetaria.setBorder(null);
        jPanel1.add(txtfNUEVOcantMonetaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 350, 45));

        txtfNUEVOfechaIngreso.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOfechaIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOfechaIngreso.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOfechaIngreso.setText("0");
        txtfNUEVOfechaIngreso.setBorder(null);
        jPanel1.add(txtfNUEVOfechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 350, 45));

        txtfNUEVOorigenIngreso.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOorigenIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOorigenIngreso.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOorigenIngreso.setText("0");
        txtfNUEVOorigenIngreso.setBorder(null);
        jPanel1.add(txtfNUEVOorigenIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 350, 45));

        txtfNUEVOtipoIngreso.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOtipoIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOtipoIngreso.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOtipoIngreso.setText("0");
        txtfNUEVOtipoIngreso.setBorder(null);
        jPanel1.add(txtfNUEVOtipoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 350, 45));

        txtfNUEVOmetodoPagoIngreso.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOmetodoPagoIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOmetodoPagoIngreso.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOmetodoPagoIngreso.setText("0");
        txtfNUEVOmetodoPagoIngreso.setBorder(null);
        jPanel1.add(txtfNUEVOmetodoPagoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 350, 45));

        btnEditarIngreso.setBackground(new java.awt.Color(127, 156, 90));
        btnEditarIngreso.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEditarIngreso.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarIngreso.setText("Editar ingreso");
        btnEditarIngreso.setBorder(null);
        btnEditarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioINgresoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioINgresoEditarActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioINgresoEditarActionPerformed

    public JLabel getLbIDingreso() {
        return lbIDingreso;
    }

    public void setLbIDingreso(JLabel lbIDingreso) {
        this.lbIDingreso = lbIDingreso;
    }

    public JTextField getTxtfNUEVOareaOrigenIngreso() {
        return txtfNUEVOareaOrigenIngreso;
    }

    public void setTxtfNUEVOareaOrigenIngreso(JTextField txtfNUEVOareaOrigenIngreso) {
        this.txtfNUEVOareaOrigenIngreso = txtfNUEVOareaOrigenIngreso;
    }

    public JTextField getTxtfNUEVOcantMonetaria() {
        return txtfNUEVOcantMonetaria;
    }

    public void setTxtfNUEVOcantMonetaria(JTextField txtfNUEVOcantMonetaria) {
        this.txtfNUEVOcantMonetaria = txtfNUEVOcantMonetaria;
    }

    public JTextField getTxtfNUEVOfechaIngreso() {
        return txtfNUEVOfechaIngreso;
    }

    public void setTxtfNUEVOfechaIngreso(JTextField txtfNUEVOfechaIngreso) {
        this.txtfNUEVOfechaIngreso = txtfNUEVOfechaIngreso;
    }

    public JTextField getTxtfNUEVOmetodoPagoIngreso() {
        return txtfNUEVOmetodoPagoIngreso;
    }

    public void setTxtfNUEVOmetodoPagoIngreso(JTextField txtfNUEVOmetodoPagoIngreso) {
        this.txtfNUEVOmetodoPagoIngreso = txtfNUEVOmetodoPagoIngreso;
    }

    public JTextField getTxtfNUEVOorigenIngreso() {
        return txtfNUEVOorigenIngreso;
    }

    public void setTxtfNUEVOorigenIngreso(JTextField txtfNUEVOorigenIngreso) {
        this.txtfNUEVOorigenIngreso = txtfNUEVOorigenIngreso;
    }

    public JTextField getTxtfNUEVOtipoIngreso() {
        return txtfNUEVOtipoIngreso;
    }

    public void setTxtfNUEVOtipoIngreso(JTextField txtfNUEVOtipoIngreso) {
        this.txtfNUEVOtipoIngreso = txtfNUEVOtipoIngreso;
    }

    private void btnEditarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarIngresoActionPerformed

        ListaIngresos.getIngresosCentroComercial().get(Identificador).setCantidadMonetariaIngreso(Integer.parseInt(txtfNUEVOcantMonetaria.getText()));
        ListaIngresos.getIngresosCentroComercial().get(Identificador).setFechaIngreso(txtfNUEVOfechaIngreso.getText());
        ListaIngresos.getIngresosCentroComercial().get(Identificador).setOrigenIngreso(txtfNUEVOorigenIngreso.getText());
        ListaIngresos.getIngresosCentroComercial().get(Identificador).setTipoDeIngresoIngreso(txtfNUEVOtipoIngreso.getText());
        ListaIngresos.getIngresosCentroComercial().get(Identificador).setMetodoDePagoIngreso(txtfNUEVOmetodoPagoIngreso.getText());
        ListaIngresos.getIngresosCentroComercial().get(Identificador).setAreaOrigenIngreso(txtfNUEVOareaOrigenIngreso.getText());

        EditadoExitosamente editado = new EditadoExitosamente();

        this.dispose();

        editado.setLocationRelativeTo(null);
        editado.setResizable(false);
        editado.setVisible(true);
    }//GEN-LAST:event_btnEditarIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarIngreso;
    private javax.swing.JButton btnVolverInicioINgresoEditar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbIDingreso;
    private javax.swing.JTextField txtfNUEVOareaOrigenIngreso;
    private javax.swing.JTextField txtfNUEVOcantMonetaria;
    private javax.swing.JTextField txtfNUEVOfechaIngreso;
    private javax.swing.JTextField txtfNUEVOmetodoPagoIngreso;
    private javax.swing.JTextField txtfNUEVOorigenIngreso;
    private javax.swing.JTextField txtfNUEVOtipoIngreso;
    // End of variables declaration//GEN-END:variables
}
