/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.revisorFiscalFrame;

/**
 *
 * @author Nicolas
 */
public class RevisionMensualContratosFrame extends javax.swing.JFrame {

    /**
     * Creates new form RevisionMensualProcesosFrame
     */
    public RevisionMensualContratosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRevisionMensualContratos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnCalcularArriendoPendiente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnActualizarArriendo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnVerificarVencimientoContratos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 170));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Revision mensual de contratos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        tblRevisionMensualContratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRevisionMensualContratos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 800, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Calcular arriendo pendiente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        btnCalcularArriendoPendiente.setBackground(new java.awt.Color(153, 195, 84));
        btnCalcularArriendoPendiente.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnCalcularArriendoPendiente.setForeground(new java.awt.Color(0, 0, 0));
        btnCalcularArriendoPendiente.setText("CALCULAR");
        btnCalcularArriendoPendiente.setBorder(null);
        jPanel1.add(btnCalcularArriendoPendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 630, 160, 50));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Actualizar arriendo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, -1, -1));

        btnActualizarArriendo.setBackground(new java.awt.Color(153, 195, 84));
        btnActualizarArriendo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnActualizarArriendo.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarArriendo.setText("ACTUALIZAR");
        btnActualizarArriendo.setBorder(null);
        jPanel1.add(btnActualizarArriendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 630, 160, 50));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Verificar vencimiento contratos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, -1, -1));

        btnVerificarVencimientoContratos.setBackground(new java.awt.Color(153, 195, 84));
        btnVerificarVencimientoContratos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnVerificarVencimientoContratos.setForeground(new java.awt.Color(0, 0, 0));
        btnVerificarVencimientoContratos.setText("VERIFICAR");
        btnVerificarVencimientoContratos.setBorder(null);
        jPanel1.add(btnVerificarVencimientoContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 630, 160, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevisionMensualContratosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevisionMensualContratosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevisionMensualContratosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevisionMensualContratosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevisionMensualContratosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarArriendo;
    private javax.swing.JButton btnCalcularArriendoPendiente;
    private javax.swing.JButton btnVerificarVencimientoContratos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRevisionMensualContratos;
    // End of variables declaration//GEN-END:variables
}
