/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.administrativos.empleadosTrabajo;

import java.awt.Color;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import logica.empleados.Empleado;
import logica.empleados.ListaEmpleados;
import logica.empleados.datosEmpleadoHorario.EmpleadoTrabajoHorario;
import logica.empleados.datosEmpleadoHorario.ListaEmpleadosHorarios;
import ui.utilidades.AgregadoExitosamente;
import ui.utilidades.ErrorAlAgregar;
import ui.utilidades.Utilidades;

/**
 *
 * @author Nicolas
 */
public class AgregarEmpleadoTrabajo extends javax.swing.JFrame {

    DefaultTableModel modeloTablaEmpleados = new DefaultTableModel();

    String[] columnasEmpleadosTabla = {"Cedula", "Nombre", "Área"};

    Color colorBotonPresionado = new Color(108, 136, 69);

    Color colorBotonProveedorPresionado = new Color(153, 195, 84);

    /**
     * Creates new form AgregarEmpleadoTrabajo
     */
    public AgregarEmpleadoTrabajo() {
        initComponents();
        modeloTablaEmpleados.setColumnIdentifiers(columnasEmpleadosTabla);

        tblEmpleadosGeneral.setModel(modeloTablaEmpleados);
        tblEmpleadosGeneral.setRowHeight(45);

        Utilidades.escalarLargoTablas(columnasEmpleadosTabla.length, tblEmpleadosGeneral);
    }

    public void botonPresionado(JButton boton) {

        boton.setBackground(colorBotonPresionado);

        boton.setForeground(Color.white);

    }

    public void botonDespresionado(JButton boton) {

        boton.setBackground(Color.white);

        boton.setForeground(Color.BLACK);

    }

    public void botonProveedorDespresionado(JButton boton) {

        boton.setBackground(colorBotonProveedorPresionado);

        boton.setForeground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolverInicioRegistrarHorarioE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleadosGeneral = new javax.swing.JTable();
        btnActualizarTabla = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfFechaHorario = new javax.swing.JTextField();
        txtfNumeroIdentificacionEmple = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfAreaEmpleadoHorario = new javax.swing.JTextField();
        txtfHoraEntrada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtfNombreEmpleadoHorario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfHoraSalida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfHorasExtra = new javax.swing.JTextField();
        btnRegistrarHorario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(990, 880));
        setMinimumSize(new java.awt.Dimension(990, 880));
        setPreferredSize(new java.awt.Dimension(990, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel6.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel6.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Registrar horario de empleado");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        btnVolverInicioRegistrarHorarioE.setBackground(new java.awt.Color(127, 156, 90));
        btnVolverInicioRegistrarHorarioE.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolverInicioRegistrarHorarioE.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicioRegistrarHorarioE.setText("X");
        btnVolverInicioRegistrarHorarioE.setBorder(null);
        btnVolverInicioRegistrarHorarioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioRegistrarHorarioEActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolverInicioRegistrarHorarioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        tblEmpleadosGeneral.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tblEmpleadosGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblEmpleadosGeneral.setAutoResizeMode(0);
        jScrollPane1.setViewportView(tblEmpleadosGeneral);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 590, 290));

        btnActualizarTabla.setBackground(new java.awt.Color(153, 195, 84));
        btnActualizarTabla.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnActualizarTabla.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarTabla.setText("Actualizar tabla");
        btnActualizarTabla.setBorder(null);
        btnActualizarTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarTablaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarTablaMouseExited(evt);
            }
        });
        btnActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 990, 50));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Empleados activos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Número de identificación");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, 30));

        txtfFechaHorario.setBackground(new java.awt.Color(153, 195, 84));
        txtfFechaHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfFechaHorario.setForeground(new java.awt.Color(0, 0, 0));
        txtfFechaHorario.setText("Pendiente");
        txtfFechaHorario.setBorder(null);
        jPanel1.add(txtfFechaHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 270, 45));

        txtfNumeroIdentificacionEmple.setBackground(new java.awt.Color(153, 195, 84));
        txtfNumeroIdentificacionEmple.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNumeroIdentificacionEmple.setForeground(new java.awt.Color(0, 0, 0));
        txtfNumeroIdentificacionEmple.setText("0");
        txtfNumeroIdentificacionEmple.setBorder(null);
        jPanel1.add(txtfNumeroIdentificacionEmple, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 270, 45));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Área");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, -1, 30));

        txtfAreaEmpleadoHorario.setBackground(new java.awt.Color(153, 195, 84));
        txtfAreaEmpleadoHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfAreaEmpleadoHorario.setForeground(new java.awt.Color(0, 0, 0));
        txtfAreaEmpleadoHorario.setText("Pendiente");
        txtfAreaEmpleadoHorario.setBorder(null);
        jPanel1.add(txtfAreaEmpleadoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 270, 45));

        txtfHoraEntrada.setBackground(new java.awt.Color(153, 195, 84));
        txtfHoraEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfHoraEntrada.setForeground(new java.awt.Color(0, 0, 0));
        txtfHoraEntrada.setText("Pendiente");
        txtfHoraEntrada.setBorder(null);
        jPanel1.add(txtfHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 270, 45));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hora entrada");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, 30));

        txtfNombreEmpleadoHorario.setBackground(new java.awt.Color(153, 195, 84));
        txtfNombreEmpleadoHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNombreEmpleadoHorario.setForeground(new java.awt.Color(0, 0, 0));
        txtfNombreEmpleadoHorario.setText("Pendiente");
        txtfNombreEmpleadoHorario.setBorder(null);
        jPanel1.add(txtfNombreEmpleadoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 270, 45));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Hora salida");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 710, -1, 30));

        txtfHoraSalida.setBackground(new java.awt.Color(153, 195, 84));
        txtfHoraSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfHoraSalida.setForeground(new java.awt.Color(0, 0, 0));
        txtfHoraSalida.setText("Pendiente");
        txtfHoraSalida.setBorder(null);
        jPanel1.add(txtfHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 750, 270, 45));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Horas extra");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, 30));

        txtfHorasExtra.setBackground(new java.awt.Color(153, 195, 84));
        txtfHorasExtra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfHorasExtra.setForeground(new java.awt.Color(0, 0, 0));
        txtfHorasExtra.setText("Pendiente");
        txtfHorasExtra.setBorder(null);
        jPanel1.add(txtfHorasExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 270, 45));

        btnRegistrarHorario.setBackground(new java.awt.Color(127, 156, 90));
        btnRegistrarHorario.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRegistrarHorario.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarHorario.setText("Registrar horario");
        btnRegistrarHorario.setBorder(null);
        btnRegistrarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 810, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioRegistrarHorarioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioRegistrarHorarioEActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioRegistrarHorarioEActionPerformed

    private void btnActualizarTablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaMouseEntered
        botonPresionado(btnActualizarTabla);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaMouseEntered

    private void btnActualizarTablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaMouseExited
        botonProveedorDespresionado(btnActualizarTabla);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaMouseExited

    private void btnActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaActionPerformed

        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Cédula", "Nombre", "Área"},
                0);

        for (Map.Entry<Integer, Empleado> codigo : ListaEmpleados.getEmpleadosCentroComercial().entrySet()) {
            int clave = codigo.getKey();

            Empleado valor = codigo.getValue();

            Object[] fila = {clave, valor.getNombreEmpleado(), valor.getAreaEmpleado()};
            modelo.addRow(fila);

        }

        tblEmpleadosGeneral.setModel(modelo);
        Utilidades.escalarLargoTablas(columnasEmpleadosTabla.length, tblEmpleadosGeneral);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaActionPerformed

    private void btnRegistrarHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarHorarioActionPerformed

        ErrorAlAgregar error = new ErrorAlAgregar();

        AgregadoExitosamente bien = new AgregadoExitosamente();

        try {

            int cedulaPersonaHorario = Integer.parseInt(txtfNumeroIdentificacionEmple.getText());
            String fecha = txtfFechaHorario.getText();
            String nombreE = txtfNombreEmpleadoHorario.getText();
            String areaEm = txtfAreaEmpleadoHorario.getText();
            String horaEntrad = txtfHoraEntrada.getText();
            String horaSalid = txtfHoraSalida.getText();
            String horasExtra = txtfHorasExtra.getText();

            ListaEmpleadosHorarios.getHorariosEmpleados().put(cedulaPersonaHorario, new EmpleadoTrabajoHorario(fecha, nombreE, areaEm, horaEntrad, horaSalid, horasExtra));

            bien.setLocationRelativeTo(null);
            bien.setResizable(false);
            bien.setVisible(true);

            this.dispose();

        } catch (Exception e) {

            error.setLocationRelativeTo(null);
            error.setResizable(false);
            error.setVisible(true);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarHorarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleadoTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleadoTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleadoTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleadoTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEmpleadoTrabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTabla;
    private javax.swing.JButton btnRegistrarHorario;
    private javax.swing.JButton btnVolverInicioRegistrarHorarioE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleadosGeneral;
    private javax.swing.JTextField txtfAreaEmpleadoHorario;
    private javax.swing.JTextField txtfFechaHorario;
    private javax.swing.JTextField txtfHoraEntrada;
    private javax.swing.JTextField txtfHoraSalida;
    private javax.swing.JTextField txtfHorasExtra;
    private javax.swing.JTextField txtfNombreEmpleadoHorario;
    private javax.swing.JTextField txtfNumeroIdentificacionEmple;
    // End of variables declaration//GEN-END:variables
}
