/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.administrativos.empleadosTrabajo;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import logica.empleados.datosEmpleadoHorario.ListaEmpleadosHorarios;
import ui.utilidades.EditadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class EditarHorarioPersonal extends javax.swing.JFrame {

    private int IDeditar;
    private String fecha;
    private String nombre;
    private String area;

    public JLabel getLbAreaEmp() {
        return lbAreaEmp;
    }

    public void setLbAreaEmp(JLabel lbAreaEmp) {
        this.lbAreaEmp = lbAreaEmp;
    }

    public JLabel getLbFecha() {
        return lbFecha;
    }

    public void setLbFecha(JLabel lbFecha) {
        this.lbFecha = lbFecha;
    }

    public JLabel getLbNombreEm() {
        return lbNombreEm;
    }

    public void setLbNombreEm(JLabel lbNombreEm) {
        this.lbNombreEm = lbNombreEm;
    }

    public JLabel getLbNumeroIdentificacion() {
        return lbNumeroIdentificacion;
    }

    public void setLbNumeroIdentificacion(JLabel lbNumeroIdentificacion) {
        this.lbNumeroIdentificacion = lbNumeroIdentificacion;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getIDeditar() {
        return IDeditar;
    }

    public void setIDeditar(int IDeditar) {
        this.IDeditar = IDeditar;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public JButton getBtnVolverInicioEditarHorarioPer() {
        return btnVolverInicioEditarHorarioPer;
    }

    public void setBtnVolverInicioEditarHorarioPer(JButton btnVolverInicioEditarHorarioPer) {
        this.btnVolverInicioEditarHorarioPer = btnVolverInicioEditarHorarioPer;
    }

    public JTextField getTxtfNUEVOHoraEntrada() {
        return txtfNUEVOHoraEntrada;
    }

    public void setTxtfNUEVOHoraEntrada(JTextField txtfNUEVOHoraEntrada) {
        this.txtfNUEVOHoraEntrada = txtfNUEVOHoraEntrada;
    }

    public JTextField getTxtfNUEVOHoraSalida() {
        return txtfNUEVOHoraSalida;
    }

    public void setTxtfNUEVOHoraSalida(JTextField txtfNUEVOHoraSalida) {
        this.txtfNUEVOHoraSalida = txtfNUEVOHoraSalida;
    }

    public JTextField getTxtfNUEVOHorasExtra() {
        return txtfNUEVOHorasExtra;
    }

    public void setTxtfNUEVOHorasExtra(JTextField txtfNUEVOHorasExtra) {
        this.txtfNUEVOHorasExtra = txtfNUEVOHorasExtra;
    }

    /**
     * Creates new form EditarHorarioPersonal
     */
    public EditarHorarioPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolverInicioEditarHorarioPer = new javax.swing.JButton();
        lbAreaEmp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfNUEVOHoraEntrada = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfNUEVOHoraSalida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfNUEVOHorasExtra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbNumeroIdentificacion = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbNombreEm = new javax.swing.JLabel();
        btnEditarHorarioPFrame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(990, 884));
        setMinimumSize(new java.awt.Dimension(990, 884));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 884));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 884));
        jPanel1.setPreferredSize(new java.awt.Dimension(990, 884));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel6.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel6.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Editar horario personal");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btnVolverInicioEditarHorarioPer.setBackground(new java.awt.Color(127, 156, 90));
        btnVolverInicioEditarHorarioPer.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolverInicioEditarHorarioPer.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicioEditarHorarioPer.setText("X");
        btnVolverInicioEditarHorarioPer.setBorder(null);
        btnVolverInicioEditarHorarioPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioEditarHorarioPerActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolverInicioEditarHorarioPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        lbAreaEmp.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbAreaEmp.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbAreaEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 250, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombre");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Área");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Hora entrada");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, 30));

        txtfNUEVOHoraEntrada.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOHoraEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOHoraEntrada.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOHoraEntrada.setText("Pendiente");
        txtfNUEVOHoraEntrada.setBorder(null);
        jPanel1.add(txtfNUEVOHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 270, 45));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Hora salida");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 30));

        txtfNUEVOHoraSalida.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOHoraSalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOHoraSalida.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOHoraSalida.setText("Pendiente");
        txtfNUEVOHoraSalida.setBorder(null);
        jPanel1.add(txtfNUEVOHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 270, 45));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Horas extra");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, 30));

        txtfNUEVOHorasExtra.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOHorasExtra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOHorasExtra.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOHorasExtra.setText("Pendiente");
        txtfNUEVOHorasExtra.setBorder(null);
        jPanel1.add(txtfNUEVOHorasExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 270, 45));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Número de identificación");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        lbNumeroIdentificacion.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbNumeroIdentificacion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbNumeroIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 220, 30));

        lbFecha.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 220, 30));

        lbNombreEm.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbNombreEm.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbNombreEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 220, 30));

        btnEditarHorarioPFrame.setBackground(new java.awt.Color(127, 156, 90));
        btnEditarHorarioPFrame.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEditarHorarioPFrame.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarHorarioPFrame.setText("Editar horario");
        btnEditarHorarioPFrame.setBorder(null);
        btnEditarHorarioPFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarHorarioPFrameActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarHorarioPFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioEditarHorarioPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioEditarHorarioPerActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioEditarHorarioPerActionPerformed

    private void btnEditarHorarioPFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarHorarioPFrameActionPerformed

        ListaEmpleadosHorarios.getHorariosEmpleados().get(IDeditar).setHoraEntrada(txtfNUEVOHoraEntrada.getText());
        ListaEmpleadosHorarios.getHorariosEmpleados().get(IDeditar).setHoraSalida(txtfNUEVOHoraSalida.getText());
        ListaEmpleadosHorarios.getHorariosEmpleados().get(IDeditar).setHorasExtra(txtfNUEVOHorasExtra.getText());

        EditadoExitosamente editado = new EditadoExitosamente();

        this.dispose();

        editado.setLocationRelativeTo(null);
        editado.setResizable(false);
        editado.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarHorarioPFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarHorarioPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarHorarioPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarHorarioPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarHorarioPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarHorarioPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarHorarioPFrame;
    private javax.swing.JButton btnVolverInicioEditarHorarioPer;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbAreaEmp;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbNombreEm;
    private javax.swing.JLabel lbNumeroIdentificacion;
    private javax.swing.JTextField txtfNUEVOHoraEntrada;
    private javax.swing.JTextField txtfNUEVOHoraSalida;
    private javax.swing.JTextField txtfNUEVOHorasExtra;
    // End of variables declaration//GEN-END:variables
}
