/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.administrativos.capacitaciones;

import logica.administrativos.capacitaciones.Capacitacion;
import logica.administrativos.capacitaciones.ListaCapacitaciones;
import ui.utilidades.AgregadoExitosamente;
import ui.utilidades.ErrorAlAgregar;

/**
 *
 * @author Nicolas
 */
public class AgendarCapacitacion extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCapacitacion
     */
    public AgendarCapacitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolerInicioAgregarCapacitacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtfEmpresaEncargadaCapacitacion = new javax.swing.JTextField();
        txtfIdentificadoCapacitacion = new javax.swing.JTextField();
        txtfNombreCapacitacion = new javax.swing.JTextField();
        txtfNombreInstructor = new javax.swing.JTextField();
        txtfDescripcionCapacitacion = new javax.swing.JTextField();
        txtfAreaDirigidaCapacitacion = new javax.swing.JTextField();
        txtfFechaCapacitacion = new javax.swing.JTextField();
        txtfHoraInicioCapacitacion = new javax.swing.JTextField();
        txtfHoraFinCapacitacion = new javax.swing.JTextField();
        btnAgendarCapacitacion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtfFinalizado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(983, 880));
        setMinimumSize(new java.awt.Dimension(983, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel1.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Agendar capacitacion");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btnVolerInicioAgregarCapacitacion.setBackground(new java.awt.Color(127, 156, 90));
        btnVolerInicioAgregarCapacitacion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolerInicioAgregarCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        btnVolerInicioAgregarCapacitacion.setText("X");
        btnVolerInicioAgregarCapacitacion.setBorder(null);
        btnVolerInicioAgregarCapacitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolerInicioAgregarCapacitacionActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolerInicioAgregarCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Instructor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Descripción");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Área dirigida");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Hora inicio");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Hora fin");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Finalizado? (Si/No)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 570, -1, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Identificador");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 30));

        txtfEmpresaEncargadaCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfEmpresaEncargadaCapacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfEmpresaEncargadaCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfEmpresaEncargadaCapacitacion.setText("Pendiente");
        txtfEmpresaEncargadaCapacitacion.setBorder(null);
        jPanel1.add(txtfEmpresaEncargadaCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 350, 45));

        txtfIdentificadoCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfIdentificadoCapacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfIdentificadoCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfIdentificadoCapacitacion.setText("0");
        txtfIdentificadoCapacitacion.setBorder(null);
        jPanel1.add(txtfIdentificadoCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 350, 45));

        txtfNombreCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfNombreCapacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNombreCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfNombreCapacitacion.setText("Pendiente");
        txtfNombreCapacitacion.setBorder(null);
        jPanel1.add(txtfNombreCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 350, 45));

        txtfNombreInstructor.setBackground(new java.awt.Color(153, 195, 84));
        txtfNombreInstructor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNombreInstructor.setForeground(new java.awt.Color(0, 0, 0));
        txtfNombreInstructor.setText("Pendiente");
        txtfNombreInstructor.setBorder(null);
        jPanel1.add(txtfNombreInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 350, 45));

        txtfDescripcionCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfDescripcionCapacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfDescripcionCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfDescripcionCapacitacion.setText("Pendiente");
        txtfDescripcionCapacitacion.setBorder(null);
        jPanel1.add(txtfDescripcionCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 350, 45));

        txtfAreaDirigidaCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfAreaDirigidaCapacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfAreaDirigidaCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfAreaDirigidaCapacitacion.setText("Pendiente");
        txtfAreaDirigidaCapacitacion.setBorder(null);
        jPanel1.add(txtfAreaDirigidaCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 350, 45));

        txtfFechaCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfFechaCapacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfFechaCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfFechaCapacitacion.setText("Pendiente");
        txtfFechaCapacitacion.setBorder(null);
        jPanel1.add(txtfFechaCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 350, 45));

        txtfHoraInicioCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfHoraInicioCapacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfHoraInicioCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfHoraInicioCapacitacion.setText("0");
        txtfHoraInicioCapacitacion.setBorder(null);
        jPanel1.add(txtfHoraInicioCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 350, 45));

        txtfHoraFinCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfHoraFinCapacitacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfHoraFinCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfHoraFinCapacitacion.setText("0");
        txtfHoraFinCapacitacion.setBorder(null);
        jPanel1.add(txtfHoraFinCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 350, 45));

        btnAgendarCapacitacion.setBackground(new java.awt.Color(127, 156, 90));
        btnAgendarCapacitacion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnAgendarCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        btnAgendarCapacitacion.setText("Agendar capacitacion");
        btnAgendarCapacitacion.setBorder(null);
        btnAgendarCapacitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarCapacitacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgendarCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 730, 250, 50));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Empresa encargada");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, 30));

        txtfFinalizado.setBackground(new java.awt.Color(153, 195, 84));
        txtfFinalizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfFinalizado.setForeground(new java.awt.Color(0, 0, 0));
        txtfFinalizado.setText("Pendiente");
        txtfFinalizado.setBorder(null);
        jPanel1.add(txtfFinalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, 350, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolerInicioAgregarCapacitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolerInicioAgregarCapacitacionActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolerInicioAgregarCapacitacionActionPerformed

    private void btnAgendarCapacitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarCapacitacionActionPerformed

        ErrorAlAgregar error = new ErrorAlAgregar();

        AgregadoExitosamente bien = new AgregadoExitosamente();

        try {

            int identificador = Integer.parseInt(txtfIdentificadoCapacitacion.getText());
            String nombreCapacitacionNuevo = txtfNombreCapacitacion.getText();
            String nombreInstructorCapacitacionNuevo = txtfNombreCapacitacion.getText();
            String descripcionCapacitacionNuevo = txtfDescripcionCapacitacion.getText();
            String areaCapacitacionNueva = txtfAreaDirigidaCapacitacion.getText();
            String fechaNueva = txtfFechaCapacitacion.getText();
            int horaInicioNueva = Integer.parseInt(txtfHoraInicioCapacitacion.getText());
            int horaFinNueva = Integer.parseInt(txtfHoraFinCapacitacion.getText());
            String empresaEncargadaCapacitacionNueva = txtfEmpresaEncargadaCapacitacion.getText();
            String finalizadoNuevo = txtfFinalizado.getText();

            ListaCapacitaciones.getCapacitacionesCentroComercial().put(identificador, new Capacitacion(nombreCapacitacionNuevo, nombreInstructorCapacitacionNuevo, descripcionCapacitacionNuevo, areaCapacitacionNueva, fechaNueva, horaInicioNueva, horaFinNueva, empresaEncargadaCapacitacionNueva, finalizadoNuevo));

            bien.setLocationRelativeTo(null);
            bien.setResizable(false);
            bien.setVisible(true);

            this.dispose();

        } catch (Exception e) {

            error.setLocationRelativeTo(null);
            error.setResizable(false);
            error.setVisible(true);

        }


    }//GEN-LAST:event_btnAgendarCapacitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarCapacitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarCapacitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarCapacitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarCapacitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarCapacitacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarCapacitacion;
    private javax.swing.JButton btnVolerInicioAgregarCapacitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField txtfAreaDirigidaCapacitacion;
    private javax.swing.JTextField txtfDescripcionCapacitacion;
    private javax.swing.JTextField txtfEmpresaEncargadaCapacitacion;
    private javax.swing.JTextField txtfFechaCapacitacion;
    private javax.swing.JTextField txtfFinalizado;
    private javax.swing.JTextField txtfHoraFinCapacitacion;
    private javax.swing.JTextField txtfHoraInicioCapacitacion;
    private javax.swing.JTextField txtfIdentificadoCapacitacion;
    private javax.swing.JTextField txtfNombreCapacitacion;
    private javax.swing.JTextField txtfNombreInstructor;
    // End of variables declaration//GEN-END:variables
}
