/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.contador;

import java.awt.Color;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import logica.contador.gastos.ListaGastos;
import logica.contador.ingresos.Ingreso;
import logica.contador.ingresos.ListaIngresos;
import ui.contador.ingresos.AgregarIngresos;
import ui.contador.ingresos.BuscarIngreso;
import ui.login.Login;
import ui.utilidades.ListaVacia;

/**
 *
 * @author Nicolas
 */
public class ContadorFrame extends javax.swing.JFrame {

    Color colorBotonPresionado = new Color(108, 136, 69);

    Color colorBotonProveedorPresionado = new Color(153, 195, 84);

    DefaultTableModel modeloTablaIngresos = new DefaultTableModel();
    DefaultTableModel modeloTablaGastos = new DefaultTableModel();

    String[] columnasTablaIngresos = {"Identificación", "Cantidad monetaria", "Fecha ingreso", "Origen ingreso", "Tipo de ingreso", "Método de pago", "Área origen"};

    String[] columnasTablaGastos = {"Identificación", "Cantidad monetaria", "Fecha gasto", "Concepto gasto", "Proveedor", "Número de recibo", "Categoria", "Área destino", "Método de pago"};

    /**
     * Creates new form ContadorFrame
     */
    public ContadorFrame() {
        initComponents();

        modeloTablaIngresos.setColumnIdentifiers(columnasTablaIngresos);

        tblIngresos.setModel(modeloTablaIngresos);

        tblIngresos.setRowHeight(40);

        modeloTablaGastos.setColumnIdentifiers(columnasTablaGastos);

        tblGastos.setModel(modeloTablaGastos);

        tblGastos.setRowHeight(40);
    }

    public void botonPresionado(JButton boton) {

        boton.setBackground(colorBotonPresionado);

        boton.setForeground(Color.white);

    }

    public void botonDespresionado(JButton boton) {

        boton.setBackground(Color.white);

        boton.setForeground(Color.BLACK);

    }

    public void botonProveedorDespresionado(JButton boton) {

        boton.setBackground(colorBotonProveedorPresionado);

        boton.setForeground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionarFacturasContador = new javax.swing.JButton();
        btnGestionarIngresosContador = new javax.swing.JButton();
        btnGestionarGastosContador = new javax.swing.JButton();
        btnCerrarSesionContador = new javax.swing.JButton();
        btnIngresarEstadoFinanciero = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelGeneralContador = new javax.swing.JTabbedPane();
        panelGestionarIngresos = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnActualizarTablaIngresos = new javax.swing.JButton();
        btnRegistrarIngreso = new javax.swing.JButton();
        btnBuscarIngreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngresos = new javax.swing.JTable();
        panelGestionarGastos = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btnRegistrarGasto = new javax.swing.JButton();
        btnBuscarGasto = new javax.swing.JButton();
        btnActualizarTablaGastos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGastos = new javax.swing.JTable();
        panelGestionarFacturas = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnRegistrarFactura = new javax.swing.JButton();
        btnBuscarFactura = new javax.swing.JButton();
        btnActualizarTablaFacturas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1400, 880));
        setMinimumSize(new java.awt.Dimension(1400, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 880));
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 170));

        btnGestionarFacturasContador.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarFacturasContador.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarFacturasContador.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarFacturasContador.setText("     Gestionar facturas");
        btnGestionarFacturasContador.setBorder(null);
        btnGestionarFacturasContador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarFacturasContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarFacturasContadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarFacturasContadorMouseExited(evt);
            }
        });
        btnGestionarFacturasContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarFacturasContadorActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarFacturasContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 50));

        btnGestionarIngresosContador.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarIngresosContador.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarIngresosContador.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarIngresosContador.setText("     Gestionar ingresos");
        btnGestionarIngresosContador.setBorder(null);
        btnGestionarIngresosContador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarIngresosContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarIngresosContadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarIngresosContadorMouseExited(evt);
            }
        });
        btnGestionarIngresosContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarIngresosContadorActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarIngresosContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 280, 50));

        btnGestionarGastosContador.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarGastosContador.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarGastosContador.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarGastosContador.setText("     Gestionar gastos");
        btnGestionarGastosContador.setBorder(null);
        btnGestionarGastosContador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarGastosContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarGastosContadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarGastosContadorMouseExited(evt);
            }
        });
        btnGestionarGastosContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarGastosContadorActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarGastosContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 50));

        btnCerrarSesionContador.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesionContador.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnCerrarSesionContador.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrarSesionContador.setText("     Cerrar sesión");
        btnCerrarSesionContador.setBorder(null);
        btnCerrarSesionContador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesionContador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionContadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionContadorMouseExited(evt);
            }
        });
        btnCerrarSesionContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionContadorActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesionContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 280, 50));

        btnIngresarEstadoFinanciero.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresarEstadoFinanciero.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnIngresarEstadoFinanciero.setForeground(new java.awt.Color(0, 0, 0));
        btnIngresarEstadoFinanciero.setText("     Estado financiero");
        btnIngresarEstadoFinanciero.setBorder(null);
        btnIngresarEstadoFinanciero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIngresarEstadoFinanciero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarEstadoFinancieroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarEstadoFinancieroMouseExited(evt);
            }
        });
        jPanel2.add(btnIngresarEstadoFinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 280, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 880));

        jPanel3.setBackground(new java.awt.Color(108, 136, 69));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contador");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1320, 110));

        panelGeneralContador.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        panelGestionarIngresos.setMaximumSize(new java.awt.Dimension(1117, 770));
        panelGestionarIngresos.setMinimumSize(new java.awt.Dimension(1117, 770));
        panelGestionarIngresos.setPreferredSize(new java.awt.Dimension(1117, 770));
        panelGestionarIngresos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Gestionar ingresos");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        jPanel10.setBackground(new java.awt.Color(153, 195, 84));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizarTablaIngresos.setBackground(new java.awt.Color(153, 195, 84));
        btnActualizarTablaIngresos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnActualizarTablaIngresos.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarTablaIngresos.setText("Actualizar tabla");
        btnActualizarTablaIngresos.setBorder(null);
        btnActualizarTablaIngresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarTablaIngresosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarTablaIngresosMouseExited(evt);
            }
        });
        btnActualizarTablaIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaIngresosActionPerformed(evt);
            }
        });
        jPanel10.add(btnActualizarTablaIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 373, 50));

        btnRegistrarIngreso.setBackground(new java.awt.Color(153, 195, 84));
        btnRegistrarIngreso.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRegistrarIngreso.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarIngreso.setText("Registrar ingreso");
        btnRegistrarIngreso.setBorder(null);
        btnRegistrarIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarIngresoMouseExited(evt);
            }
        });
        btnRegistrarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarIngresoActionPerformed(evt);
            }
        });
        jPanel10.add(btnRegistrarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 373, 50));

        btnBuscarIngreso.setBackground(new java.awt.Color(153, 195, 84));
        btnBuscarIngreso.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnBuscarIngreso.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarIngreso.setText("Buscar ingreso");
        btnBuscarIngreso.setBorder(null);
        btnBuscarIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarIngresoMouseExited(evt);
            }
        });
        btnBuscarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIngresoActionPerformed(evt);
            }
        });
        jPanel10.add(btnBuscarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 380, 50));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1120, 50));

        tblIngresos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tblIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIngresos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1080, -1));

        panelGestionarIngresos.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 770));

        panelGeneralContador.addTab("tab1", panelGestionarIngresos);

        panelGestionarGastos.setMaximumSize(new java.awt.Dimension(1117, 770));
        panelGestionarGastos.setMinimumSize(new java.awt.Dimension(1117, 770));
        panelGestionarGastos.setPreferredSize(new java.awt.Dimension(1117, 770));
        panelGestionarGastos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(1117, 770));
        jPanel5.setMinimumSize(new java.awt.Dimension(1117, 770));
        jPanel5.setPreferredSize(new java.awt.Dimension(1117, 770));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(127, 156, 90));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Gestionar gastos");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        jPanel11.setBackground(new java.awt.Color(153, 195, 84));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarGasto.setBackground(new java.awt.Color(153, 195, 84));
        btnRegistrarGasto.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRegistrarGasto.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarGasto.setText("Registrar gasto");
        btnRegistrarGasto.setBorder(null);
        btnRegistrarGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarGastoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarGastoMouseExited(evt);
            }
        });
        btnRegistrarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarGastoActionPerformed(evt);
            }
        });
        jPanel11.add(btnRegistrarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 373, 50));

        btnBuscarGasto.setBackground(new java.awt.Color(153, 195, 84));
        btnBuscarGasto.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnBuscarGasto.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarGasto.setText("Buscar gasto");
        btnBuscarGasto.setBorder(null);
        btnBuscarGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarGastoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarGastoMouseExited(evt);
            }
        });
        btnBuscarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGastoActionPerformed(evt);
            }
        });
        jPanel11.add(btnBuscarGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 380, 50));

        btnActualizarTablaGastos.setBackground(new java.awt.Color(153, 195, 84));
        btnActualizarTablaGastos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnActualizarTablaGastos.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarTablaGastos.setText("Actualizar tabla");
        btnActualizarTablaGastos.setBorder(null);
        btnActualizarTablaGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarTablaGastosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarTablaGastosMouseExited(evt);
            }
        });
        jPanel11.add(btnActualizarTablaGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 373, 50));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1120, 50));

        tblGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblGastos);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1080, -1));

        panelGestionarGastos.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 770));

        panelGeneralContador.addTab("tab2", panelGestionarGastos);

        panelGestionarFacturas.setMaximumSize(new java.awt.Dimension(1117, 770));
        panelGestionarFacturas.setMinimumSize(new java.awt.Dimension(1117, 770));
        panelGestionarFacturas.setPreferredSize(new java.awt.Dimension(1117, 770));
        panelGestionarFacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMaximumSize(new java.awt.Dimension(1117, 770));
        jPanel8.setMinimumSize(new java.awt.Dimension(1117, 770));
        jPanel8.setPreferredSize(new java.awt.Dimension(1117, 770));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(127, 156, 90));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Gestionar facturas");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        jPanel12.setBackground(new java.awt.Color(153, 195, 84));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarFactura.setBackground(new java.awt.Color(153, 195, 84));
        btnRegistrarFactura.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRegistrarFactura.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarFactura.setText("Registrar factura");
        btnRegistrarFactura.setBorder(null);
        btnRegistrarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarFacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarFacturaMouseExited(evt);
            }
        });
        jPanel12.add(btnRegistrarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 373, 50));

        btnBuscarFactura.setBackground(new java.awt.Color(153, 195, 84));
        btnBuscarFactura.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnBuscarFactura.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarFactura.setText("Buscar factura");
        btnBuscarFactura.setBorder(null);
        btnBuscarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarFacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarFacturaMouseExited(evt);
            }
        });
        jPanel12.add(btnBuscarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 373, 50));

        btnActualizarTablaFacturas.setBackground(new java.awt.Color(153, 195, 84));
        btnActualizarTablaFacturas.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnActualizarTablaFacturas.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarTablaFacturas.setText("Actualizar tabla");
        btnActualizarTablaFacturas.setBorder(null);
        btnActualizarTablaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarTablaFacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarTablaFacturasMouseExited(evt);
            }
        });
        jPanel12.add(btnActualizarTablaFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 373, 50));

        jPanel8.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1120, 50));

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblFacturas);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1080, -1));

        panelGestionarFacturas.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 770));

        panelGeneralContador.addTab("tab3", panelGestionarFacturas);

        jPanel1.add(panelGeneralContador, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 1170, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarFacturasContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarFacturasContadorActionPerformed
//        panelGeneralContador.setSelectedIndex(2);        // este todavia no
    }//GEN-LAST:event_btnGestionarFacturasContadorActionPerformed

    private void btnGestionarIngresosContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarIngresosContadorActionPerformed
        panelGeneralContador.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarIngresosContadorActionPerformed

    private void btnGestionarGastosContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarGastosContadorActionPerformed
        panelGeneralContador.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarGastosContadorActionPerformed

    private void btnGestionarIngresosContadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarIngresosContadorMouseEntered
        botonPresionado(btnGestionarIngresosContador);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarIngresosContadorMouseEntered

    private void btnGestionarIngresosContadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarIngresosContadorMouseExited
        botonDespresionado(btnGestionarIngresosContador);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarIngresosContadorMouseExited

    private void btnGestionarGastosContadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarGastosContadorMouseEntered

        botonPresionado(btnGestionarGastosContador);// TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarGastosContadorMouseEntered

    private void btnGestionarGastosContadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarGastosContadorMouseExited

        botonDespresionado(btnGestionarGastosContador);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarGastosContadorMouseExited

    private void btnGestionarFacturasContadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarFacturasContadorMouseEntered

        botonPresionado(btnGestionarFacturasContador);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarFacturasContadorMouseEntered

    private void btnGestionarFacturasContadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarFacturasContadorMouseExited
        botonDespresionado(btnGestionarFacturasContador);// TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarFacturasContadorMouseExited

    private void btnCerrarSesionContadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionContadorMouseEntered
        botonPresionado(btnCerrarSesionContador);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionContadorMouseEntered

    private void btnCerrarSesionContadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionContadorMouseExited
        botonDespresionado(btnCerrarSesionContador);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionContadorMouseExited

    private void btnCerrarSesionContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionContadorActionPerformed
        Login login = new Login();

        login.setLocationRelativeTo(null);
        login.setResizable(false);
        login.setVisible(true);

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionContadorActionPerformed

    private void btnActualizarTablaIngresosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaIngresosMouseEntered
        botonPresionado(btnActualizarTablaIngresos);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaIngresosMouseEntered

    private void btnActualizarTablaIngresosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaIngresosMouseExited
        botonProveedorDespresionado(btnActualizarTablaIngresos);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaIngresosMouseExited

    private void btnRegistrarIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarIngresoMouseEntered
        botonPresionado(btnRegistrarIngreso);// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarIngresoMouseEntered

    private void btnRegistrarIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarIngresoMouseExited

        botonProveedorDespresionado(btnRegistrarIngreso);// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarIngresoMouseExited

    private void btnBuscarIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarIngresoMouseEntered

        botonPresionado(btnBuscarIngreso);
// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarIngresoMouseEntered

    private void btnBuscarIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarIngresoMouseExited
        botonProveedorDespresionado(btnBuscarIngreso);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarIngresoMouseExited

    private void btnBuscarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGastoActionPerformed

        ListaVacia vacia = new ListaVacia();

        if (ListaGastos.getGastosCentroComercial().isEmpty()) {

            vacia.setLocationRelativeTo(null);
            vacia.setResizable(false);
            vacia.setVisible(true);

        } else {
//            buscarP.setLocationRelativeTo(null);
//            buscarP.setResizable(false);
//            buscarP.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarGastoActionPerformed

    private void btnRegistrarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarGastoActionPerformed

    private void btnActualizarTablaGastosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaGastosMouseEntered
        botonPresionado(btnActualizarTablaGastos);// TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaGastosMouseEntered

    private void btnActualizarTablaGastosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaGastosMouseExited
        botonProveedorDespresionado(btnActualizarTablaGastos);// TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaGastosMouseExited

    private void btnRegistrarGastoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarGastoMouseEntered
        botonPresionado(btnRegistrarGasto);// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarGastoMouseEntered

    private void btnRegistrarGastoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarGastoMouseExited
        botonProveedorDespresionado(btnRegistrarGasto);// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarGastoMouseExited

    private void btnBuscarGastoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarGastoMouseEntered
        botonPresionado(btnBuscarGasto);// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarGastoMouseEntered

    private void btnBuscarGastoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarGastoMouseExited
        botonProveedorDespresionado(btnBuscarGasto);// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarGastoMouseExited

    private void btnActualizarTablaFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaFacturasMouseEntered
        botonPresionado(btnActualizarTablaFacturas);// TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaFacturasMouseEntered

    private void btnActualizarTablaFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaFacturasMouseExited
        botonProveedorDespresionado(btnActualizarTablaFacturas);// TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaFacturasMouseExited

    private void btnRegistrarFacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarFacturaMouseEntered
        botonPresionado(btnRegistrarFactura);// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarFacturaMouseEntered

    private void btnRegistrarFacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarFacturaMouseExited
        botonProveedorDespresionado(btnRegistrarFactura);// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarFacturaMouseExited

    private void btnBuscarFacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarFacturaMouseEntered
        botonPresionado(btnBuscarFactura);// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarFacturaMouseEntered

    private void btnBuscarFacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarFacturaMouseExited
        botonProveedorDespresionado(btnBuscarFactura);// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarFacturaMouseExited

    private void btnIngresarEstadoFinancieroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarEstadoFinancieroMouseEntered
        botonPresionado(btnIngresarEstadoFinanciero);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarEstadoFinancieroMouseEntered

    private void btnIngresarEstadoFinancieroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarEstadoFinancieroMouseExited
        botonDespresionado(btnIngresarEstadoFinanciero);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarEstadoFinancieroMouseExited

    private void btnBuscarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIngresoActionPerformed

        ListaVacia vacia = new ListaVacia();

        BuscarIngreso buscarIn = new BuscarIngreso();

        if (ListaIngresos.getIngresosCentroComercial().isEmpty()) {

            vacia.setLocationRelativeTo(null);
            vacia.setResizable(false);
            vacia.setVisible(true);

        } else {

            buscarIn.setLocationRelativeTo(null);
            buscarIn.setResizable(false);
            buscarIn.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarIngresoActionPerformed

    private void btnRegistrarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarIngresoActionPerformed
        AgregarIngresos agregarIngreso = new AgregarIngresos();
        agregarIngreso.setLocationRelativeTo(null);
        agregarIngreso.setResizable(false);
        agregarIngreso.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarIngresoActionPerformed

    private void btnActualizarTablaIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaIngresosActionPerformed

        llenarTablaIngresos();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaIngresosActionPerformed

    public void llenarTablaIngresos() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Identificación", "Cantidad monetaria", "Fecha ingreso", "Origen ingreso", "Tipo de ingreso", "Método de pago", "Área origen"},
                0);

        for (Map.Entry<Integer, Ingreso> codigo : ListaIngresos.getIngresosCentroComercial().entrySet()) {
            int clave = codigo.getKey();

            Ingreso valor = codigo.getValue();

            Object[] fila = {clave, valor.getCantidadMonetariaIngreso(), valor.getFechaIngreso(), valor.getOrigenIngreso(), valor.getTipoDeIngresoIngreso(), valor.getMetodoDePagoIngreso(), valor.getAreaOrigenIngreso()};
            modelo.addRow(fila);

        }

        tblIngresos.setModel(modelo);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTablaFacturas;
    private javax.swing.JButton btnActualizarTablaGastos;
    private javax.swing.JButton btnActualizarTablaIngresos;
    private javax.swing.JButton btnBuscarFactura;
    private javax.swing.JButton btnBuscarGasto;
    private javax.swing.JButton btnBuscarIngreso;
    private javax.swing.JButton btnCerrarSesionContador;
    private javax.swing.JButton btnGestionarFacturasContador;
    private javax.swing.JButton btnGestionarGastosContador;
    private javax.swing.JButton btnGestionarIngresosContador;
    private javax.swing.JButton btnIngresarEstadoFinanciero;
    private javax.swing.JButton btnRegistrarFactura;
    private javax.swing.JButton btnRegistrarGasto;
    private javax.swing.JButton btnRegistrarIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane panelGeneralContador;
    private javax.swing.JPanel panelGestionarFacturas;
    private javax.swing.JPanel panelGestionarGastos;
    private javax.swing.JPanel panelGestionarIngresos;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JTable tblGastos;
    private javax.swing.JTable tblIngresos;
    // End of variables declaration//GEN-END:variables
}
