/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.administrativos;

import java.awt.Color;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import logica.administrativos.ListaProveedores;
import logica.administrativos.Proveedor;
import ui.administrativos.proveedores.AdministrativosAgregarProveedor;
import ui.administrativos.proveedores.BuscarProveedor;
import ui.administrativos.proveedores.EliminarProveedor;
import ui.administrativos.proveedores.IndiceEditarProveeedor;
import ui.login.Login;
import ui.utilidades.ListaVacia;

/**
 *
 * @author Nicolas
 */
public class AdministrativosFrame extends javax.swing.JFrame {

    Color colorBotonPresionado = new Color(108, 136, 69);

    Color colorBotonProveedorPresionado = new Color(153, 195, 84);

    DefaultTableModel modelo = new DefaultTableModel();

    String[] columnas = {"Identificación Fiscal", "Nombre empresa", "Dirección registrada", "Número contacto", "Dirección de correo", "Servicio suministrado", "Referencia comercial", "Término de pago"};

    /**
     * Creates new form AdministrativosFrame
     */
    public AdministrativosFrame() {
        initComponents();

        modelo.setColumnIdentifiers(columnas);

        tblProveedores.setModel(modelo);

        tblProveedores.setRowHeight(40);

//        GestionarPersonalFrame gestionarPersonal = new GestionarPersonalFrame();
//
//        gestionarPersonal.setSize(1120, 770);
//        gestionarPersonal.setLocation(0, 0);
//
//        content.removeAll();
//        content.add(gestionarPersonal, BorderLayout.CENTER);
//        content.revalidate();
//        content.repaint();
    }

    public void botonPresionado(JButton boton) {

        boton.setBackground(colorBotonPresionado);

        boton.setForeground(Color.white);

    }

    public void botonDespresionado(JButton boton) {

        boton.setBackground(Color.white);

        boton.setForeground(Color.BLACK);

    }

    public void botonProveedorDespresionado(JButton boton) {

        boton.setBackground(colorBotonProveedorPresionado);

        boton.setForeground(Color.BLACK);

    }

    public void llenarTablaProveedores() {
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"Identificación Fiscal", "Nombre empresa", "Dirección registrada", "Número contacto", "Dirección de correo", "Servicio suministrado", "Referencia comercial", "Término de pago"},
                0);

        for (Map.Entry<Integer, Proveedor> codigo : ListaProveedores.getProveedoresCentroComercial().entrySet()) {
            int clave = codigo.getKey();

            Proveedor valor = codigo.getValue();

            Object[] fila = {clave, valor.getNombreEmpresaProveedor(), valor.getDireccionRegistradaProveedor(), valor.getNumeroContactoProveedor(), valor.getDireccionCorreoProveedor(), valor.getServicioSuministradoProveedor(), valor.getReferenciaComercialProveedor(), valor.getTerminoDePagoProveedor()};
            modelo.addRow(fila);

        }

        tblProveedores.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionarEmpleados2 = new javax.swing.JButton();
        btnRegistrarHorarioPersonal = new javax.swing.JButton();
        btnGestionarEventos = new javax.swing.JButton();
        btnGestionarEncuentrosCapacitacion = new javax.swing.JButton();
        btnProveedoresAdmin = new javax.swing.JButton();
        btnRegresarInicioAdmin = new javax.swing.JButton();
        panelGeneralAdmin = new javax.swing.JTabbedPane();
        gestionarPersonalFrame = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonal = new javax.swing.JTable();
        btnGestionarEmpleado = new javax.swing.JButton();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        gestionarHorarioPersonal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHorarioPersonal = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnGestionarHorasPersonal = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnAgregarHorasExtra = new javax.swing.JButton();
        gestionarEventos = new javax.swing.JPanel();
        btnEliminarEvento = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGestionarEventos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnGestionarEvento = new javax.swing.JButton();
        btnAgregarEvento = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        gestionarCapacitacion = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCapacitaciones = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        btnGestionarCapacitacion = new javax.swing.JButton();
        btnAgregarCapacitacion = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnEliminarCapacitacion = new javax.swing.JButton();
        gestionarProveedores = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnActualizarTablaProveedores = new javax.swing.JButton();
        btnAgregarProveedor = new javax.swing.JButton();
        btnBuscarProveedor = new javax.swing.JButton();
        btnGestionarProveedores = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1400, 880));
        setMinimumSize(new java.awt.Dimension(1400, 880));
        setPreferredSize(new java.awt.Dimension(1400, 880));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(108, 136, 69));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Administrativos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1320, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        btnGestionarEmpleados2.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarEmpleados2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarEmpleados2.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarEmpleados2.setText("     Gestionar personal");
        btnGestionarEmpleados2.setBorder(null);
        btnGestionarEmpleados2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarEmpleados2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionarEmpleados2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarEmpleados2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarEmpleados2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGestionarEmpleados2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnGestionarEmpleados2MouseReleased(evt);
            }
        });
        btnGestionarEmpleados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarEmpleados2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarEmpleados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 280, 50));

        btnRegistrarHorarioPersonal.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarHorarioPersonal.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRegistrarHorarioPersonal.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrarHorarioPersonal.setText("     Horario del personal");
        btnRegistrarHorarioPersonal.setBorder(null);
        btnRegistrarHorarioPersonal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrarHorarioPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarHorarioPersonalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarHorarioPersonalMouseExited(evt);
            }
        });
        btnRegistrarHorarioPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarHorarioPersonalActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarHorarioPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 50));

        btnGestionarEventos.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarEventos.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarEventos.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarEventos.setText("     Gestionar eventos");
        btnGestionarEventos.setBorder(null);
        btnGestionarEventos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarEventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarEventosMouseExited(evt);
            }
        });
        btnGestionarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarEventosActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 50));

        btnGestionarEncuentrosCapacitacion.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarEncuentrosCapacitacion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarEncuentrosCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarEncuentrosCapacitacion.setText("     Encuentros de capacitación");
        btnGestionarEncuentrosCapacitacion.setBorder(null);
        btnGestionarEncuentrosCapacitacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarEncuentrosCapacitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarEncuentrosCapacitacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarEncuentrosCapacitacionMouseExited(evt);
            }
        });
        btnGestionarEncuentrosCapacitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarEncuentrosCapacitacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnGestionarEncuentrosCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 280, 50));

        btnProveedoresAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnProveedoresAdmin.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnProveedoresAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnProveedoresAdmin.setText("     Proveedores");
        btnProveedoresAdmin.setBorder(null);
        btnProveedoresAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedoresAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedoresAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProveedoresAdminMouseExited(evt);
            }
        });
        btnProveedoresAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnProveedoresAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 280, 50));

        btnRegresarInicioAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresarInicioAdmin.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRegresarInicioAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarInicioAdmin.setText("     Cerrar sesión");
        btnRegresarInicioAdmin.setBorder(null);
        btnRegresarInicioAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegresarInicioAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarInicioAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarInicioAdminMouseExited(evt);
            }
        });
        btnRegresarInicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarInicioAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegresarInicioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 280, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 880));

        panelGeneralAdmin.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        panelGeneralAdmin.setTabPlacement(javax.swing.JTabbedPane.RIGHT);

        gestionarPersonalFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Gestionar personal");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tblPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPersonal);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 800, -1));

        btnGestionarEmpleado.setBackground(new java.awt.Color(153, 195, 84));
        btnGestionarEmpleado.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarEmpleado.setText("GESTIONAR EMPLEADO");
        btnGestionarEmpleado.setBorder(null);
        jPanel3.add(btnGestionarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 250, 50));

        btnAgregarEmpleado.setBackground(new java.awt.Color(153, 195, 84));
        btnAgregarEmpleado.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnAgregarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarEmpleado.setText("AGREGAR EMPLEADO");
        btnAgregarEmpleado.setBorder(null);
        jPanel3.add(btnAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 230, 50));

        btnEliminarEmpleado.setBackground(new java.awt.Color(153, 195, 84));
        btnEliminarEmpleado.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEliminarEmpleado.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarEmpleado.setText("ELIMINAR EMPLEADO");
        btnEliminarEmpleado.setBorder(null);
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 220, 50));

        gestionarPersonalFrame.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 780));

        panelGeneralAdmin.addTab("tab1", gestionarPersonalFrame);

        gestionarHorarioPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Registrar horario personal");
        gestionarHorarioPersonal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        tblHorarioPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblHorarioPersonal);

        gestionarHorarioPersonal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 800, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Gestionar horas");
        gestionarHorarioPersonal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, -1, -1));

        btnGestionarHorasPersonal.setBackground(new java.awt.Color(153, 195, 84));
        btnGestionarHorasPersonal.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarHorasPersonal.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarHorasPersonal.setText("ENTRAR");
        btnGestionarHorasPersonal.setBorder(null);
        gestionarHorarioPersonal.add(btnGestionarHorasPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 160, 50));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Agregar horas extra");
        gestionarHorarioPersonal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, -1, -1));

        btnAgregarHorasExtra.setBackground(new java.awt.Color(153, 195, 84));
        btnAgregarHorasExtra.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnAgregarHorasExtra.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarHorasExtra.setText("AGREGAR");
        btnAgregarHorasExtra.setBorder(null);
        gestionarHorarioPersonal.add(btnAgregarHorasExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 160, 50));

        panelGeneralAdmin.addTab("tab2", gestionarHorarioPersonal);

        gestionarEventos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarEvento.setBackground(new java.awt.Color(153, 195, 84));
        btnEliminarEvento.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEliminarEvento.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarEvento.setText("ELIMINAR");
        btnEliminarEvento.setBorder(null);
        gestionarEventos.add(btnEliminarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 610, 160, 50));

        tblGestionarEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblGestionarEventos);

        gestionarEventos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 800, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Agregar evento");
        gestionarEventos.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Gestionar evento");
        gestionarEventos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, -1));

        btnGestionarEvento.setBackground(new java.awt.Color(153, 195, 84));
        btnGestionarEvento.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarEvento.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarEvento.setText("GESTIONAR");
        btnGestionarEvento.setBorder(null);
        gestionarEventos.add(btnGestionarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, 160, 50));

        btnAgregarEvento.setBackground(new java.awt.Color(153, 195, 84));
        btnAgregarEvento.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnAgregarEvento.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarEvento.setText("AGREGAR");
        btnAgregarEvento.setBorder(null);
        gestionarEventos.add(btnAgregarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 160, 50));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Eliminar evento");
        gestionarEventos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Eventos");
        gestionarEventos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        panelGeneralAdmin.addTab("tab3", gestionarEventos);

        gestionarCapacitacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Gestionar capacitacion");
        gestionarCapacitacion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        tblCapacitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblCapacitaciones);

        gestionarCapacitacion.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 800, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Gestionar datos empleado");
        gestionarCapacitacion.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        btnGestionarCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        btnGestionarCapacitacion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarCapacitacion.setText("GESTIONAR");
        btnGestionarCapacitacion.setBorder(null);
        gestionarCapacitacion.add(btnGestionarCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 160, 50));

        btnAgregarCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        btnAgregarCapacitacion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnAgregarCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarCapacitacion.setText("AGENDAR");
        btnAgregarCapacitacion.setBorder(null);
        gestionarCapacitacion.add(btnAgregarCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 160, 50));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Agregar capacitacion");
        gestionarCapacitacion.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, -1, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Eliminar empleado");
        gestionarCapacitacion.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 570, -1, -1));

        btnEliminarCapacitacion.setBackground(new java.awt.Color(153, 195, 84));
        btnEliminarCapacitacion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEliminarCapacitacion.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarCapacitacion.setText("ELIMINAR");
        btnEliminarCapacitacion.setBorder(null);
        gestionarCapacitacion.add(btnEliminarCapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 610, 160, 50));

        panelGeneralAdmin.addTab("tab4", gestionarCapacitacion);

        gestionarProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProveedores.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tblProveedores);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 1080, 520));

        jPanel5.setBackground(new java.awt.Color(153, 195, 84));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizarTablaProveedores.setBackground(new java.awt.Color(153, 195, 84));
        btnActualizarTablaProveedores.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnActualizarTablaProveedores.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarTablaProveedores.setText("Actualizar tabla");
        btnActualizarTablaProveedores.setBorder(null);
        btnActualizarTablaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarTablaProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarTablaProveedoresMouseExited(evt);
            }
        });
        btnActualizarTablaProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaProveedoresActionPerformed(evt);
            }
        });
        jPanel5.add(btnActualizarTablaProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 224, 50));

        btnAgregarProveedor.setBackground(new java.awt.Color(153, 195, 84));
        btnAgregarProveedor.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnAgregarProveedor.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarProveedor.setText("Agregar proveedor");
        btnAgregarProveedor.setBorder(null);
        btnAgregarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarProveedorMouseExited(evt);
            }
        });
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });
        jPanel5.add(btnAgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 224, 50));

        btnBuscarProveedor.setBackground(new java.awt.Color(153, 195, 84));
        btnBuscarProveedor.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnBuscarProveedor.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarProveedor.setText("Buscar proveedor");
        btnBuscarProveedor.setBorder(null);
        btnBuscarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarProveedorMouseExited(evt);
            }
        });
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 224, 50));

        btnGestionarProveedores.setBackground(new java.awt.Color(153, 195, 84));
        btnGestionarProveedores.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnGestionarProveedores.setForeground(new java.awt.Color(0, 0, 0));
        btnGestionarProveedores.setText("Gestionar proveedor");
        btnGestionarProveedores.setBorder(null);
        btnGestionarProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionarProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionarProveedoresMouseExited(evt);
            }
        });
        btnGestionarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProveedoresActionPerformed(evt);
            }
        });
        jPanel5.add(btnGestionarProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 224, 50));

        btnEliminarProveedor.setBackground(new java.awt.Color(153, 195, 84));
        btnEliminarProveedor.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEliminarProveedor.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarProveedor.setText("Eliminar proveedor");
        btnEliminarProveedor.setBorder(null);
        btnEliminarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarProveedorMouseExited(evt);
            }
        });
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });
        jPanel5.add(btnEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 230, 50));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1120, 50));

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Gestionar proveedores");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 90));

        gestionarProveedores.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 770));

        panelGeneralAdmin.addTab("tab5", gestionarProveedores);

        getContentPane().add(panelGeneralAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 1180, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarEmpleados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEmpleados2ActionPerformed
        panelGeneralAdmin.setSelectedIndex(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEmpleados2ActionPerformed

    private void btnGestionarEncuentrosCapacitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEncuentrosCapacitacionActionPerformed
        panelGeneralAdmin.setSelectedIndex(3);// TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEncuentrosCapacitacionActionPerformed

    private void btnGestionarEmpleados2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEmpleados2MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEmpleados2MouseClicked

    private void btnGestionarEmpleados2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEmpleados2MousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEmpleados2MousePressed

    private void btnGestionarEmpleados2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEmpleados2MouseReleased
//

    }//GEN-LAST:event_btnGestionarEmpleados2MouseReleased

    private void btnGestionarEmpleados2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEmpleados2MouseEntered
        botonPresionado(btnGestionarEmpleados2);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEmpleados2MouseEntered

    private void btnGestionarEmpleados2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEmpleados2MouseExited

        botonDespresionado(btnGestionarEmpleados2);

// TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEmpleados2MouseExited

    private void btnRegistrarHorarioPersonalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarHorarioPersonalMouseEntered
        botonPresionado(btnRegistrarHorarioPersonal);

// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarHorarioPersonalMouseEntered

    private void btnRegistrarHorarioPersonalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarHorarioPersonalMouseExited
        botonDespresionado(btnRegistrarHorarioPersonal);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarHorarioPersonalMouseExited

    private void btnGestionarEventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEventosMouseEntered

        botonPresionado(btnGestionarEventos);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEventosMouseEntered

    private void btnGestionarEventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEventosMouseExited

        botonDespresionado(btnGestionarEventos);
// TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEventosMouseExited

    private void btnGestionarEncuentrosCapacitacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEncuentrosCapacitacionMouseEntered

        botonPresionado(btnGestionarEncuentrosCapacitacion);
// TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEncuentrosCapacitacionMouseEntered

    private void btnGestionarEncuentrosCapacitacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarEncuentrosCapacitacionMouseExited
        botonDespresionado(btnGestionarEncuentrosCapacitacion);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEncuentrosCapacitacionMouseExited

    private void btnProveedoresAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresAdminActionPerformed
        panelGeneralAdmin.setSelectedIndex(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProveedoresAdminActionPerformed

    private void btnProveedoresAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresAdminMouseEntered
        botonPresionado(btnProveedoresAdmin);

// TODO add your handling code here:
    }//GEN-LAST:event_btnProveedoresAdminMouseEntered

    private void btnProveedoresAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresAdminMouseExited
        botonDespresionado(btnProveedoresAdmin);// TODO add your handling code here:
    }//GEN-LAST:event_btnProveedoresAdminMouseExited

    private void btnRegistrarHorarioPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarHorarioPersonalActionPerformed
        panelGeneralAdmin.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarHorarioPersonalActionPerformed

    private void btnGestionarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarEventosActionPerformed
        panelGeneralAdmin.setSelectedIndex(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarEventosActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void btnRegresarInicioAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarInicioAdminMouseEntered
        botonPresionado(btnRegresarInicioAdmin);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarInicioAdminMouseEntered

    private void btnRegresarInicioAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarInicioAdminMouseExited
        botonDespresionado(btnRegresarInicioAdmin);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarInicioAdminMouseExited

    private void btnRegresarInicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarInicioAdminActionPerformed
        Login login = new Login();

        login.setLocationRelativeTo(null);
        login.setResizable(false);
        login.setVisible(true);

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarInicioAdminActionPerformed

    private void btnAgregarProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseEntered
        botonPresionado(btnAgregarProveedor);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProveedorMouseEntered

    private void btnAgregarProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProveedorMouseExited
        botonProveedorDespresionado(btnAgregarProveedor);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProveedorMouseExited

    private void btnGestionarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProveedoresActionPerformed

        IndiceEditarProveeedor IDeditar = new IndiceEditarProveeedor();

        ListaVacia listav = new ListaVacia();

        if (ListaProveedores.getProveedoresCentroComercial().isEmpty()) {
            listav.setLocationRelativeTo(null);
            listav.setResizable(false);
            listav.setVisible(true);
        } else {

            IDeditar.setLocationRelativeTo(null);
            IDeditar.setResizable(false);
            IDeditar.setVisible(true);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarProveedoresActionPerformed

    private void btnGestionarProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarProveedoresMouseEntered
        botonPresionado(btnGestionarProveedores);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarProveedoresMouseEntered

    private void btnGestionarProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarProveedoresMouseExited

        botonProveedorDespresionado(btnGestionarProveedores);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionarProveedoresMouseExited

    private void btnEliminarProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProveedorMouseEntered

        botonPresionado(btnEliminarProveedor);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProveedorMouseEntered

    private void btnEliminarProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarProveedorMouseExited
        botonProveedorDespresionado(btnEliminarProveedor);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProveedorMouseExited

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        AdministrativosAgregarProveedor adminAgregarProv = new AdministrativosAgregarProveedor();

        adminAgregarProv.setLocationRelativeTo(null);
        adminAgregarProv.setResizable(false);
        adminAgregarProv.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void btnBuscarProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProveedorMouseEntered
        botonPresionado(btnBuscarProveedor);

// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProveedorMouseEntered

    private void btnBuscarProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarProveedorMouseExited
        botonProveedorDespresionado(btnBuscarProveedor);

// TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProveedorMouseExited

    private void btnActualizarTablaProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaProveedoresActionPerformed
        ListaVacia lv = new ListaVacia();
        if (ListaProveedores.getProveedoresCentroComercial().isEmpty()) {
            lv.setLocationRelativeTo(null);
            lv.setResizable(false);
            lv.setVisible(true);
        } else {
            llenarTablaProveedores();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaProveedoresActionPerformed

    private void btnActualizarTablaProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaProveedoresMouseEntered

        botonPresionado(btnActualizarTablaProveedores);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaProveedoresMouseEntered

    private void btnActualizarTablaProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarTablaProveedoresMouseExited

        botonProveedorDespresionado(btnActualizarTablaProveedores);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarTablaProveedoresMouseExited

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed

        EliminarProveedor elim = new EliminarProveedor();

        ListaVacia vacia = new ListaVacia();

        if (ListaProveedores.getProveedoresCentroComercial().isEmpty()) {
            vacia.setLocationRelativeTo(null);
            vacia.setResizable(false);
            vacia.setVisible(true);

        } else {
            elim.setLocationRelativeTo(null);
            elim.setResizable(false);
            elim.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed

        BuscarProveedor buscarP = new BuscarProveedor();
        ListaVacia vacia = new ListaVacia();

        if (ListaProveedores.getProveedoresCentroComercial().isEmpty()) {
            vacia.setLocationRelativeTo(null);
            vacia.setResizable(false);
            vacia.setVisible(true);

        } else {

            buscarP.setLocationRelativeTo(null);
            buscarP.setResizable(false);
            buscarP.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrativosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrativosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrativosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrativosFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrativosFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTablaProveedores;
    private javax.swing.JButton btnAgregarCapacitacion;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnAgregarEvento;
    private javax.swing.JButton btnAgregarHorasExtra;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnEliminarCapacitacion;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnEliminarEvento;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnGestionarCapacitacion;
    private javax.swing.JButton btnGestionarEmpleado;
    private javax.swing.JButton btnGestionarEmpleados2;
    private javax.swing.JButton btnGestionarEncuentrosCapacitacion;
    private javax.swing.JButton btnGestionarEvento;
    private javax.swing.JButton btnGestionarEventos;
    private javax.swing.JButton btnGestionarHorasPersonal;
    private javax.swing.JButton btnGestionarProveedores;
    private javax.swing.JButton btnProveedoresAdmin;
    private javax.swing.JButton btnRegistrarHorarioPersonal;
    private javax.swing.JButton btnRegresarInicioAdmin;
    private javax.swing.JPanel gestionarCapacitacion;
    private javax.swing.JPanel gestionarEventos;
    private javax.swing.JPanel gestionarHorarioPersonal;
    private javax.swing.JPanel gestionarPersonalFrame;
    private javax.swing.JPanel gestionarProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane panelGeneralAdmin;
    private javax.swing.JTable tblCapacitaciones;
    private javax.swing.JTable tblGestionarEventos;
    private javax.swing.JTable tblHorarioPersonal;
    private javax.swing.JTable tblPersonal;
    private javax.swing.JTable tblProveedores;
    // End of variables declaration//GEN-END:variables
}
