/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.seguridad.incidentes;

import javax.swing.table.DefaultTableModel;
import logica.seguridad.incidentes.ListaIncidentes;
import ui.utilidades.EliminadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class GestionarIncidente extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    String[] columnas = {"Identificación", "Nombre área", "Hora", "Descripción", "Personas involucradas", "Acciones tomadas", "Daños materiales", "Notificación autoridades?"};

    /**
     * Creates new form GestionarIncidente
     */
    public GestionarIncidente() {
        initComponents();

        modelo.setColumnIdentifiers(columnas);

        tblUnicoIncidente.setRowHeight(45);
        tblUnicoIncidente.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnSalirVentanaGEstiIncidente = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtfBuscarIncidente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnicoIncidente = new javax.swing.JTable();
        btnBuscarINcidenteID = new javax.swing.JButton();
        btnEliminarIncidente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1120, 550));
        setMinimumSize(new java.awt.Dimension(1120, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMinimumSize(new java.awt.Dimension(1120, 90));
        jPanel6.setPreferredSize(new java.awt.Dimension(1120, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Incidente");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        btnSalirVentanaGEstiIncidente.setBackground(new java.awt.Color(127, 156, 90));
        btnSalirVentanaGEstiIncidente.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnSalirVentanaGEstiIncidente.setForeground(new java.awt.Color(0, 0, 0));
        btnSalirVentanaGEstiIncidente.setText("X");
        btnSalirVentanaGEstiIncidente.setBorder(null);
        btnSalirVentanaGEstiIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVentanaGEstiIncidenteActionPerformed(evt);
            }
        });
        jPanel6.add(btnSalirVentanaGEstiIncidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 90));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Número de identificación ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtfBuscarIncidente.setBackground(new java.awt.Color(153, 195, 84));
        txtfBuscarIncidente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfBuscarIncidente.setForeground(new java.awt.Color(0, 0, 0));
        txtfBuscarIncidente.setBorder(null);
        jPanel1.add(txtfBuscarIncidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 350, 45));

        tblUnicoIncidente.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tblUnicoIncidente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUnicoIncidente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 1090, 80));

        btnBuscarINcidenteID.setBackground(new java.awt.Color(127, 156, 90));
        btnBuscarINcidenteID.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnBuscarINcidenteID.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarINcidenteID.setText("Buscar");
        btnBuscarINcidenteID.setBorder(null);
        btnBuscarINcidenteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarINcidenteIDActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarINcidenteID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 45));

        btnEliminarIncidente.setBackground(new java.awt.Color(127, 156, 90));
        btnEliminarIncidente.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEliminarIncidente.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarIncidente.setText("Eliminarla");
        btnEliminarIncidente.setBorder(null);
        btnEliminarIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarIncidenteActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarIncidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 130, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirVentanaGEstiIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVentanaGEstiIncidenteActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirVentanaGEstiIncidenteActionPerformed

    private void btnBuscarINcidenteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarINcidenteIDActionPerformed

        int ID = Integer.parseInt(txtfBuscarIncidente.getText());

        Object[] ob = {ID, ListaIncidentes.getIncidentesCentroComercial().get(ID).getNombreAreaIncidente(), ListaIncidentes.getIncidentesCentroComercial().get(ID).getFechaIncidente(), ListaIncidentes.getIncidentesCentroComercial().get(ID).getHoraIndicente(), ListaIncidentes.getIncidentesCentroComercial().get(ID).getDescripcionIncidente(), ListaIncidentes.getIncidentesCentroComercial().get(ID).getPersonasInvolucradasIncidente(), ListaIncidentes.getIncidentesCentroComercial().get(ID).getAccionesTomadasIncidente(), ListaIncidentes.getIncidentesCentroComercial().get(ID).getDanosMaterialesIncidente(), ListaIncidentes.getIncidentesCentroComercial().get(ID).getNotificacionAutoridadesIncidente()};

        modelo.addRow(ob);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarINcidenteIDActionPerformed

    private void btnEliminarIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarIncidenteActionPerformed
        int ID = Integer.parseInt(txtfBuscarIncidente.getText());

        ListaIncidentes.getIncidentesCentroComercial().remove(ID);

        this.dispose();
        EliminadoExitosamente elim = new EliminadoExitosamente();

        elim.setLocationRelativeTo(null);
        elim.setResizable(false);
        elim.setVisible(true);
    }//GEN-LAST:event_btnEliminarIncidenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarIncidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarIncidente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarINcidenteID;
    private javax.swing.JButton btnEliminarIncidente;
    private javax.swing.JButton btnSalirVentanaGEstiIncidente;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUnicoIncidente;
    private javax.swing.JTextField txtfBuscarIncidente;
    // End of variables declaration//GEN-END:variables
}
