/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.administrativos.convenios;

import javax.swing.JLabel;
import javax.swing.JTextField;
import logica.administrativos.convenios.ListaConvenios;
import ui.utilidades.EditadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class EditarConvenio extends javax.swing.JFrame {

    private int IDeditar;

    public int getIDeditar() {
        return IDeditar;
    }

    public void setIDeditar(int IDeditar) {
        this.IDeditar = IDeditar;
    }

    /**
     * Creates new form EditarConvenio
     */
    public EditarConvenio() {
        initComponents();
    }

    public JLabel getLbNumIdentificacionConvenio() {
        return lbNumIdentificacionConvenio;
    }

    public void setLbNumIdentificacionConvenio(JLabel lbNumIdentificacionConvenio) {
        this.lbNumIdentificacionConvenio = lbNumIdentificacionConvenio;
    }

    public JTextField getTxtfNUEVOBeneficiosMutuos() {
        return txtfNUEVOBeneficiosMutuos;
    }

    public void setTxtfNUEVOBeneficiosMutuos(JTextField txtfNUEVOBeneficiosMutuos) {
        this.txtfNUEVOBeneficiosMutuos = txtfNUEVOBeneficiosMutuos;
    }

    public JTextField getTxtfNUEVOCedulaFirmanteConvenio() {
        return txtfNUEVOCedulaFirmanteConvenio;
    }

    public void setTxtfNUEVOCedulaFirmanteConvenio(JTextField txtfNUEVOCedulaFirmanteConvenio) {
        this.txtfNUEVOCedulaFirmanteConvenio = txtfNUEVOCedulaFirmanteConvenio;
    }

    public JTextField getTxtfNUEVOClausulasCondiciones() {
        return txtfNUEVOClausulasCondiciones;
    }

    public void setTxtfNUEVOClausulasCondiciones(JTextField txtfNUEVOClausulasCondiciones) {
        this.txtfNUEVOClausulasCondiciones = txtfNUEVOClausulasCondiciones;
    }

    public JTextField getTxtfNUEVOClausulasConfidencialidad() {
        return txtfNUEVOClausulasConfidencialidad;
    }

    public void setTxtfNUEVOClausulasConfidencialidad(JTextField txtfNUEVOClausulasConfidencialidad) {
        this.txtfNUEVOClausulasConfidencialidad = txtfNUEVOClausulasConfidencialidad;
    }

    public JTextField getTxtfNUEVOCompensacion() {
        return txtfNUEVOCompensacion;
    }

    public void setTxtfNUEVOCompensacion(JTextField txtfNUEVOCompensacion) {
        this.txtfNUEVOCompensacion = txtfNUEVOCompensacion;
    }

    public JTextField getTxtfNUEVODuracionConvenio() {
        return txtfNUEVODuracionConvenio;
    }

    public void setTxtfNUEVODuracionConvenio(JTextField txtfNUEVODuracionConvenio) {
        this.txtfNUEVODuracionConvenio = txtfNUEVODuracionConvenio;
    }

    public JTextField getTxtfNUEVOFechaConvenio() {
        return txtfNUEVOFechaConvenio;
    }

    public void setTxtfNUEVOFechaConvenio(JTextField txtfNUEVOFechaConvenio) {
        this.txtfNUEVOFechaConvenio = txtfNUEVOFechaConvenio;
    }

    public JTextField getTxtfNUEVOLeyesAplicables() {
        return txtfNUEVOLeyesAplicables;
    }

    public void setTxtfNUEVOLeyesAplicables(JTextField txtfNUEVOLeyesAplicables) {
        this.txtfNUEVOLeyesAplicables = txtfNUEVOLeyesAplicables;
    }

    public JTextField getTxtfNUEVONombreConvenio() {
        return txtfNUEVONombreConvenio;
    }

    public void setTxtfNUEVONombreConvenio(JTextField txtfNUEVONombreConvenio) {
        this.txtfNUEVONombreConvenio = txtfNUEVONombreConvenio;
    }

    public JTextField getTxtfNUEVONombreFirmanteConvenio() {
        return txtfNUEVONombreFirmanteConvenio;
    }

    public void setTxtfNUEVONombreFirmanteConvenio(JTextField txtfNUEVONombreFirmanteConvenio) {
        this.txtfNUEVONombreFirmanteConvenio = txtfNUEVONombreFirmanteConvenio;
    }

    public JTextField getTxtfNUEVOObjetivoConvenio() {
        return txtfNUEVOObjetivoConvenio;
    }

    public void setTxtfNUEVOObjetivoConvenio(JTextField txtfNUEVOObjetivoConvenio) {
        this.txtfNUEVOObjetivoConvenio = txtfNUEVOObjetivoConvenio;
    }

    public JTextField getTxtfNUEVOPartesInvolucradas() {
        return txtfNUEVOPartesInvolucradas;
    }

    public void setTxtfNUEVOPartesInvolucradas(JTextField txtfNUEVOPartesInvolucradas) {
        this.txtfNUEVOPartesInvolucradas = txtfNUEVOPartesInvolucradas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolverInicioEditarConvenio = new javax.swing.JButton();
        lbNumIdentificacionConvenio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfNUEVONombreConvenio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfNUEVONombreFirmanteConvenio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfNUEVOCedulaFirmanteConvenio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfNUEVOFechaConvenio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfNUEVOPartesInvolucradas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtfNUEVOLeyesAplicables = new javax.swing.JTextField();
        txtfNUEVOClausulasConfidencialidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtfNUEVOCompensacion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtfNUEVOBeneficiosMutuos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfNUEVOClausulasCondiciones = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtfNUEVOObjetivoConvenio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfNUEVODuracionConvenio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEditarConvenioEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(990, 880));
        setMinimumSize(new java.awt.Dimension(990, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel6.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel6.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Editar convenio");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btnVolverInicioEditarConvenio.setBackground(new java.awt.Color(127, 156, 90));
        btnVolverInicioEditarConvenio.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolverInicioEditarConvenio.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicioEditarConvenio.setText("X");
        btnVolverInicioEditarConvenio.setBorder(null);
        btnVolverInicioEditarConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioEditarConvenioActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolverInicioEditarConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        lbNumIdentificacionConvenio.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbNumIdentificacionConvenio.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbNumIdentificacionConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 270, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre del convenio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 30));

        txtfNUEVONombreConvenio.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVONombreConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVONombreConvenio.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVONombreConvenio.setText("Pendiente");
        txtfNUEVONombreConvenio.setBorder(null);
        jPanel1.add(txtfNUEVONombreConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 350, 45));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre del firmante");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, 30));

        txtfNUEVONombreFirmanteConvenio.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVONombreFirmanteConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVONombreFirmanteConvenio.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVONombreFirmanteConvenio.setText("Pendiente");
        txtfNUEVONombreFirmanteConvenio.setBorder(null);
        jPanel1.add(txtfNUEVONombreFirmanteConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 350, 45));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cedula del firmante");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, 30));

        txtfNUEVOCedulaFirmanteConvenio.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOCedulaFirmanteConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOCedulaFirmanteConvenio.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOCedulaFirmanteConvenio.setText("Pendiente");
        txtfNUEVOCedulaFirmanteConvenio.setBorder(null);
        jPanel1.add(txtfNUEVOCedulaFirmanteConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 350, 45));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha inicio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, 30));

        txtfNUEVOFechaConvenio.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOFechaConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOFechaConvenio.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOFechaConvenio.setText("Pendiente");
        txtfNUEVOFechaConvenio.setBorder(null);
        jPanel1.add(txtfNUEVOFechaConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 350, 45));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Partes involucradas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, 30));

        txtfNUEVOPartesInvolucradas.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOPartesInvolucradas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOPartesInvolucradas.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOPartesInvolucradas.setText("Pendiente");
        txtfNUEVOPartesInvolucradas.setBorder(null);
        jPanel1.add(txtfNUEVOPartesInvolucradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 700, 350, 45));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Leyes aplicables");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 770, -1, 30));

        txtfNUEVOLeyesAplicables.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOLeyesAplicables.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOLeyesAplicables.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOLeyesAplicables.setText("Pendiente");
        txtfNUEVOLeyesAplicables.setBorder(null);
        jPanel1.add(txtfNUEVOLeyesAplicables, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 810, 350, 45));

        txtfNUEVOClausulasConfidencialidad.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOClausulasConfidencialidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOClausulasConfidencialidad.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOClausulasConfidencialidad.setText("Pendiente");
        txtfNUEVOClausulasConfidencialidad.setBorder(null);
        jPanel1.add(txtfNUEVOClausulasConfidencialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 700, 350, 45));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Clausulas de confidencialidad");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 660, -1, 30));

        txtfNUEVOCompensacion.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOCompensacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOCompensacion.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOCompensacion.setText("0");
        txtfNUEVOCompensacion.setBorder(null);
        jPanel1.add(txtfNUEVOCompensacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 350, 45));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Compensación");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, 30));

        txtfNUEVOBeneficiosMutuos.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOBeneficiosMutuos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOBeneficiosMutuos.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOBeneficiosMutuos.setText("Pendiente");
        txtfNUEVOBeneficiosMutuos.setBorder(null);
        jPanel1.add(txtfNUEVOBeneficiosMutuos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 350, 45));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Beneficios mutuos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, 30));

        txtfNUEVOClausulasCondiciones.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOClausulasCondiciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOClausulasCondiciones.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOClausulasCondiciones.setText("Pendiente");
        txtfNUEVOClausulasCondiciones.setBorder(null);
        jPanel1.add(txtfNUEVOClausulasCondiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 350, 45));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Clausulas o condiciones");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 30));

        txtfNUEVOObjetivoConvenio.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOObjetivoConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOObjetivoConvenio.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOObjetivoConvenio.setText("Pendiente");
        txtfNUEVOObjetivoConvenio.setBorder(null);
        jPanel1.add(txtfNUEVOObjetivoConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 350, 45));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Objetivo del convenio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, 30));

        txtfNUEVODuracionConvenio.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVODuracionConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVODuracionConvenio.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVODuracionConvenio.setText("Pendiente");
        txtfNUEVODuracionConvenio.setBorder(null);
        jPanel1.add(txtfNUEVODuracionConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 350, 45));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Duración del convenio");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, 30));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Número de identificación");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 30));

        btnEditarConvenioEnviar.setBackground(new java.awt.Color(127, 156, 90));
        btnEditarConvenioEnviar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEditarConvenioEnviar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarConvenioEnviar.setText("Editar convenio");
        btnEditarConvenioEnviar.setBorder(null);
        btnEditarConvenioEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarConvenioEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarConvenioEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 790, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioEditarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioEditarConvenioActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioEditarConvenioActionPerformed

    private void btnEditarConvenioEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarConvenioEnviarActionPerformed

        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setNombreConvenio(txtfNUEVONombreConvenio.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setNombreFirmante(txtfNUEVONombreFirmanteConvenio.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setCedulaFirmante(txtfNUEVOCedulaFirmanteConvenio.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setFechaFirma(txtfNUEVOFechaConvenio.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setPartesInvolucradas(txtfNUEVOPartesInvolucradas.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setDuracionConvenio(txtfNUEVODuracionConvenio.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setObjetivo(txtfNUEVOObjetivoConvenio.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setClausulasOcondiciones(txtfNUEVOClausulasCondiciones.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setBeneficiosMutuos(txtfNUEVOBeneficiosMutuos.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setCompensacionConvenio(Integer.parseInt(txtfNUEVOCompensacion.getText()));
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setClausulasConfidencialidad(txtfNUEVOClausulasConfidencialidad.getText());
        ListaConvenios.getListaConveniosCentroComercial().get(IDeditar).setLeyesAplicables(txtfNUEVOLeyesAplicables.getText());

        EditadoExitosamente editado = new EditadoExitosamente();

        this.dispose();

        editado.setLocationRelativeTo(null);
        editado.setResizable(false);
        editado.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarConvenioEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarConvenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarConvenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarConvenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarConvenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarConvenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarConvenioEnviar;
    private javax.swing.JButton btnVolverInicioEditarConvenio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbNumIdentificacionConvenio;
    private javax.swing.JTextField txtfNUEVOBeneficiosMutuos;
    private javax.swing.JTextField txtfNUEVOCedulaFirmanteConvenio;
    private javax.swing.JTextField txtfNUEVOClausulasCondiciones;
    private javax.swing.JTextField txtfNUEVOClausulasConfidencialidad;
    private javax.swing.JTextField txtfNUEVOCompensacion;
    private javax.swing.JTextField txtfNUEVODuracionConvenio;
    private javax.swing.JTextField txtfNUEVOFechaConvenio;
    private javax.swing.JTextField txtfNUEVOLeyesAplicables;
    private javax.swing.JTextField txtfNUEVONombreConvenio;
    private javax.swing.JTextField txtfNUEVONombreFirmanteConvenio;
    private javax.swing.JTextField txtfNUEVOObjetivoConvenio;
    private javax.swing.JTextField txtfNUEVOPartesInvolucradas;
    // End of variables declaration//GEN-END:variables
}
