/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.administrativos.convenios;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logica.administrativos.convenios.ListaConvenios;
import ui.utilidades.EliminadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class GestionarConvenio extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();

    String[] columnas = {"Identificación", "Nombre convenio", "Nombre firmante", "Cedula firmante", "Fecha firmante", "Partes involucradas", "Duración", "Objetivo", "Clausulas", "Beneficios", "Compensación", "Confidencialidad", "Leyes aplicables"};

    /**
     * Creates new form GestionarConvenio
     */
    public GestionarConvenio() {
        initComponents();
        modelo.setColumnIdentifiers(columnas);
        tblUnicoConvenio.setModel(modelo);
        tblUnicoConvenio.setRowHeight(45);

        escalarLargoTablas(columnas.length, tblUnicoConvenio);

    }

    public void escalarLargoTablas(int tamanoColumnas, JTable tabla) {
        for (int i = 0; i < tamanoColumnas; i++) {
            tabla.getColumnModel().getColumn(i).setPreferredWidth(200);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtfBuscarConvenio = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnSalirVentanaGestiLimpieza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnicoConvenio = new javax.swing.JTable();
        btnBuscarConvenioID = new javax.swing.JButton();
        btnEliminarConvenio = new javax.swing.JButton();
        btnEditarConvenio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1120, 550));
        setMinimumSize(new java.awt.Dimension(1120, 550));
        setPreferredSize(new java.awt.Dimension(1120, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1120, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(1120, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Número de identificación ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtfBuscarConvenio.setBackground(new java.awt.Color(153, 195, 84));
        txtfBuscarConvenio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfBuscarConvenio.setForeground(new java.awt.Color(0, 0, 0));
        txtfBuscarConvenio.setBorder(null);
        jPanel1.add(txtfBuscarConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 350, 45));

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMinimumSize(new java.awt.Dimension(1120, 90));
        jPanel6.setPreferredSize(new java.awt.Dimension(1120, 90));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Convenio");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        btnSalirVentanaGestiLimpieza.setBackground(new java.awt.Color(127, 156, 90));
        btnSalirVentanaGestiLimpieza.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnSalirVentanaGestiLimpieza.setForeground(new java.awt.Color(0, 0, 0));
        btnSalirVentanaGestiLimpieza.setText("X");
        btnSalirVentanaGestiLimpieza.setBorder(null);
        btnSalirVentanaGestiLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirVentanaGestiLimpiezaActionPerformed(evt);
            }
        });
        jPanel6.add(btnSalirVentanaGestiLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 90));

        tblUnicoConvenio.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        tblUnicoConvenio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUnicoConvenio.setAutoResizeMode(0);
        jScrollPane1.setViewportView(tblUnicoConvenio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 1090, 80));

        btnBuscarConvenioID.setBackground(new java.awt.Color(127, 156, 90));
        btnBuscarConvenioID.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnBuscarConvenioID.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarConvenioID.setText("Buscar");
        btnBuscarConvenioID.setBorder(null);
        btnBuscarConvenioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarConvenioIDActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarConvenioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, 45));

        btnEliminarConvenio.setBackground(new java.awt.Color(127, 156, 90));
        btnEliminarConvenio.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEliminarConvenio.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarConvenio.setText("Eliminarlo");
        btnEliminarConvenio.setBorder(null);
        btnEliminarConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarConvenioActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 130, 45));

        btnEditarConvenio.setBackground(new java.awt.Color(127, 156, 90));
        btnEditarConvenio.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEditarConvenio.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarConvenio.setText("Editarlo");
        btnEditarConvenio.setBorder(null);
        btnEditarConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarConvenioActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarConvenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 130, 45));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirVentanaGestiLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirVentanaGestiLimpiezaActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirVentanaGestiLimpiezaActionPerformed

    private void btnBuscarConvenioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarConvenioIDActionPerformed

        int ID = Integer.parseInt(txtfBuscarConvenio.getText());

        Object[] ob = {ID, ListaConvenios.getListaConveniosCentroComercial().get(ID).getNombreConvenio(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getNombreFirmante(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getCedulaFirmante(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getFechaFirma(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getPartesInvolucradas(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getDuracionConvenio(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getObjetivo(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getClausulasOcondiciones(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getBeneficiosMutuos(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getCompensacionConvenio(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getClausulasConfidencialidad(), ListaConvenios.getListaConveniosCentroComercial().get(ID).getLeyesAplicables()};

        modelo.addRow(ob);
        escalarLargoTablas(columnas.length, tblUnicoConvenio);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarConvenioIDActionPerformed

    private void btnEliminarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarConvenioActionPerformed
        int ID = Integer.parseInt(txtfBuscarConvenio.getText());

        ListaConvenios.getListaConveniosCentroComercial().remove(ID);

        this.dispose();
        EliminadoExitosamente elim = new EliminadoExitosamente();

        elim.setLocationRelativeTo(null);
        elim.setResizable(false);
        elim.setVisible(true);
    }//GEN-LAST:event_btnEliminarConvenioActionPerformed

    private void btnEditarConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarConvenioActionPerformed

        int ID = Integer.parseInt(txtfBuscarConvenio.getText());

        EditarConvenio editarConv = new EditarConvenio();

        editarConv.getLbNumIdentificacionConvenio().setText(String.valueOf(ID));

        editarConv.getTxtfNUEVONombreConvenio().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getNombreConvenio());

        editarConv.getTxtfNUEVONombreFirmanteConvenio().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getNombreFirmante());
        editarConv.getTxtfNUEVOCedulaFirmanteConvenio().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getCedulaFirmante());
        editarConv.getTxtfNUEVOFechaConvenio().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getFechaFirma());
        editarConv.getTxtfNUEVOPartesInvolucradas().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getPartesInvolucradas());
        editarConv.getTxtfNUEVODuracionConvenio().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getDuracionConvenio());
        editarConv.getTxtfNUEVOObjetivoConvenio().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getObjetivo());
        editarConv.getTxtfNUEVOClausulasCondiciones().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getClausulasOcondiciones());
        editarConv.getTxtfNUEVOBeneficiosMutuos().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getBeneficiosMutuos());
        editarConv.getTxtfNUEVOCompensacion().setText(String.valueOf(ListaConvenios.getListaConveniosCentroComercial().get(ID).getCompensacionConvenio()));
        editarConv.getTxtfNUEVOClausulasConfidencialidad().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getClausulasConfidencialidad());
        editarConv.getTxtfNUEVOLeyesAplicables().setText(ListaConvenios.getListaConveniosCentroComercial().get(ID).getLeyesAplicables());

        editarConv.setIDeditar(ID);

        this.dispose();

        editarConv.setLocationRelativeTo(null);
        editarConv.setResizable(false);
        editarConv.setVisible(true);
        // APENAS LE DE ACA A TODOS LOS TXTFIELD PONERLE LOS GETTER
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarConvenioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarConvenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarConvenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarConvenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarConvenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarConvenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarConvenioID;
    private javax.swing.JButton btnEditarConvenio;
    private javax.swing.JButton btnEliminarConvenio;
    private javax.swing.JButton btnSalirVentanaGestiLimpieza;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUnicoConvenio;
    private javax.swing.JTextField txtfBuscarConvenio;
    // End of variables declaration//GEN-END:variables
}
