/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.mantenimiento.mantenimientos;

import javax.swing.JLabel;
import javax.swing.JTextField;
import logica.mantenimiento.mantenimientos.ListaMantenimientos;
import ui.utilidades.EditadoExitosamente;

/**
 *
 * @author Nicolas
 */
public class EditarMantenimiento extends javax.swing.JFrame {

    private int IDeditar;

    public int getIDeditar() {
        return IDeditar;
    }

    public void setIDeditar(int IDeditar) {
        this.IDeditar = IDeditar;
    }

    public JLabel getLbNumIdMantenimiento() {
        return lbNumIdMantenimiento;
    }

    public void setLbNumIdMantenimiento(JLabel lbNumIdMantenimiento) {
        this.lbNumIdMantenimiento = lbNumIdMantenimiento;
    }

    public JTextField getTxtfNUEVOCedulaPersonaMantenimiento() {
        return txtfNUEVOCedulaPersonaMantenimiento;
    }

    public void setTxtfNUEVOCedulaPersonaMantenimiento(JTextField txtfNUEVOCedulaPersonaMantenimiento) {
        this.txtfNUEVOCedulaPersonaMantenimiento = txtfNUEVOCedulaPersonaMantenimiento;
    }

    public JTextField getTxtfNUEVODescripcionMantenimiento() {
        return txtfNUEVODescripcionMantenimiento;
    }

    public void setTxtfNUEVODescripcionMantenimiento(JTextField txtfNUEVODescripcionMantenimiento) {
        this.txtfNUEVODescripcionMantenimiento = txtfNUEVODescripcionMantenimiento;
    }

    public JTextField getTxtfNUEVOFechaFinalizacionMantenimiento() {
        return txtfNUEVOFechaFinalizacionMantenimiento;
    }

    public void setTxtfNUEVOFechaFinalizacionMantenimiento(JTextField txtfNUEVOFechaFinalizacionMantenimiento) {
        this.txtfNUEVOFechaFinalizacionMantenimiento = txtfNUEVOFechaFinalizacionMantenimiento;
    }

    public JTextField getTxtfNUEVOFinalizadoMantenimiento() {
        return txtfNUEVOFinalizadoMantenimiento;
    }

    public void setTxtfNUEVOFinalizadoMantenimiento(JTextField txtfNUEVOFinalizadoMantenimiento) {
        this.txtfNUEVOFinalizadoMantenimiento = txtfNUEVOFinalizadoMantenimiento;
    }

    public JTextField getTxtfNUEVOHoraFinalizacionMantenimiento() {
        return txtfNUEVOHoraFinalizacionMantenimiento;
    }

    public void setTxtfNUEVOHoraFinalizacionMantenimiento(JTextField txtfNUEVOHoraFinalizacionMantenimiento) {
        this.txtfNUEVOHoraFinalizacionMantenimiento = txtfNUEVOHoraFinalizacionMantenimiento;
    }

    public JTextField getTxtfNUEVONombreMantenimiento() {
        return txtfNUEVONombreMantenimiento;
    }

    public void setTxtfNUEVONombreMantenimiento(JTextField txtfNUEVONombreMantenimiento) {
        this.txtfNUEVONombreMantenimiento = txtfNUEVONombreMantenimiento;
    }

    public JTextField getTxtfNUEVOPersonaEncargadaMantenimiento() {
        return txtfNUEVOPersonaEncargadaMantenimiento;
    }

    public void setTxtfNUEVOPersonaEncargadaMantenimiento(JTextField txtfNUEVOPersonaEncargadaMantenimiento) {
        this.txtfNUEVOPersonaEncargadaMantenimiento = txtfNUEVOPersonaEncargadaMantenimiento;
    }

    public JTextField getTxtfNUEVOZonaMantenimiento() {
        return txtfNUEVOZonaMantenimiento;
    }

    public void setTxtfNUEVOZonaMantenimiento(JTextField txtfNUEVOZonaMantenimiento) {
        this.txtfNUEVOZonaMantenimiento = txtfNUEVOZonaMantenimiento;
    }

    /**
     * Creates new form EditarMantenimiento
     */
    public EditarMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        btnVolverInicioEditarManteni = new javax.swing.JButton();
        lbNumIdMantenimiento = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfNUEVONombreMantenimiento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfNUEVOPersonaEncargadaMantenimiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfNUEVOCedulaPersonaMantenimiento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfNUEVODescripcionMantenimiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfNUEVOFinalizadoMantenimiento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfNUEVOZonaMantenimiento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtfNUEVOHoraFinalizacionMantenimiento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfNUEVOFechaFinalizacionMantenimiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEditarMatenimientoNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(990, 880));
        setMinimumSize(new java.awt.Dimension(990, 880));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 880));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 880));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(127, 156, 90));
        jPanel6.setMaximumSize(new java.awt.Dimension(983, 880));
        jPanel6.setMinimumSize(new java.awt.Dimension(983, 880));
        jPanel6.setPreferredSize(new java.awt.Dimension(983, 880));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Editar mantenimiento");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btnVolverInicioEditarManteni.setBackground(new java.awt.Color(127, 156, 90));
        btnVolverInicioEditarManteni.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        btnVolverInicioEditarManteni.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverInicioEditarManteni.setText("X");
        btnVolverInicioEditarManteni.setBorder(null);
        btnVolverInicioEditarManteni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioEditarManteniActionPerformed(evt);
            }
        });
        jPanel6.add(btnVolverInicioEditarManteni, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 90));

        lbNumIdMantenimiento.setFont(new java.awt.Font("Microsoft JhengHei", 0, 18)); // NOI18N
        lbNumIdMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbNumIdMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 300, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre del mantenimiento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 30));

        txtfNUEVONombreMantenimiento.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVONombreMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVONombreMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVONombreMantenimiento.setText("Pendiente");
        txtfNUEVONombreMantenimiento.setBorder(null);
        jPanel1.add(txtfNUEVONombreMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 350, 45));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Persona encargada");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 30));

        txtfNUEVOPersonaEncargadaMantenimiento.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOPersonaEncargadaMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOPersonaEncargadaMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOPersonaEncargadaMantenimiento.setText("Pendiente");
        txtfNUEVOPersonaEncargadaMantenimiento.setBorder(null);
        jPanel1.add(txtfNUEVOPersonaEncargadaMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 350, 45));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cédula");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, 30));

        txtfNUEVOCedulaPersonaMantenimiento.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOCedulaPersonaMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOCedulaPersonaMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOCedulaPersonaMantenimiento.setText("0");
        txtfNUEVOCedulaPersonaMantenimiento.setBorder(null);
        jPanel1.add(txtfNUEVOCedulaPersonaMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 350, 45));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Descripción del mantenimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, 30));

        txtfNUEVODescripcionMantenimiento.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVODescripcionMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVODescripcionMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVODescripcionMantenimiento.setText("Pendiente");
        txtfNUEVODescripcionMantenimiento.setBorder(null);
        jPanel1.add(txtfNUEVODescripcionMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, 350, 45));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Finalizado? (Si/No)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, 30));

        txtfNUEVOFinalizadoMantenimiento.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOFinalizadoMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOFinalizadoMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOFinalizadoMantenimiento.setText("Pendiente");
        txtfNUEVOFinalizadoMantenimiento.setBorder(null);
        jPanel1.add(txtfNUEVOFinalizadoMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 350, 45));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Zona");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, 30));

        txtfNUEVOZonaMantenimiento.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOZonaMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOZonaMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOZonaMantenimiento.setText("Pendiente");
        txtfNUEVOZonaMantenimiento.setBorder(null);
        jPanel1.add(txtfNUEVOZonaMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 350, 45));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Hora finalización");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, -1, 30));

        txtfNUEVOHoraFinalizacionMantenimiento.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOHoraFinalizacionMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOHoraFinalizacionMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOHoraFinalizacionMantenimiento.setText("Pendiente");
        txtfNUEVOHoraFinalizacionMantenimiento.setBorder(null);
        jPanel1.add(txtfNUEVOHoraFinalizacionMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 350, 45));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha finalización");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, -1, 30));

        txtfNUEVOFechaFinalizacionMantenimiento.setBackground(new java.awt.Color(153, 195, 84));
        txtfNUEVOFechaFinalizacionMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtfNUEVOFechaFinalizacionMantenimiento.setForeground(new java.awt.Color(0, 0, 0));
        txtfNUEVOFechaFinalizacionMantenimiento.setText("Pendiente");
        txtfNUEVOFechaFinalizacionMantenimiento.setBorder(null);
        jPanel1.add(txtfNUEVOFechaFinalizacionMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 350, 45));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Número de identificación");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 30));

        btnEditarMatenimientoNuevo.setBackground(new java.awt.Color(127, 156, 90));
        btnEditarMatenimientoNuevo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEditarMatenimientoNuevo.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarMatenimientoNuevo.setText("Editar matenimiento");
        btnEditarMatenimientoNuevo.setBorder(null);
        btnEditarMatenimientoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMatenimientoNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarMatenimientoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverInicioEditarManteniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioEditarManteniActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverInicioEditarManteniActionPerformed

    private void btnEditarMatenimientoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMatenimientoNuevoActionPerformed

        ListaMantenimientos.getMantenimientosCentroComercial().get(IDeditar).setNombreMantenimiento(txtfNUEVONombreMantenimiento.getText());

        ListaMantenimientos.getMantenimientosCentroComercial().get(IDeditar).setEncargadoMantenimiento(txtfNUEVOPersonaEncargadaMantenimiento.getText());

        ListaMantenimientos.getMantenimientosCentroComercial().get(IDeditar).setCedulaEncargado(Integer.parseInt(txtfNUEVOCedulaPersonaMantenimiento.getText()));

        ListaMantenimientos.getMantenimientosCentroComercial().get(IDeditar).setDescripcionMantenimiento(txtfNUEVODescripcionMantenimiento.getText());

        ListaMantenimientos.getMantenimientosCentroComercial().get(IDeditar).setFinalizadoMantenimiento(txtfNUEVOFinalizadoMantenimiento.getText());

        ListaMantenimientos.getMantenimientosCentroComercial().get(IDeditar).setZonaMantenimiento(txtfNUEVOZonaMantenimiento.getText());
        ListaMantenimientos.getMantenimientosCentroComercial().get(IDeditar).setHoraFinalizacion(txtfNUEVOHoraFinalizacionMantenimiento.getText());
        ListaMantenimientos.getMantenimientosCentroComercial().get(IDeditar).setFechaFinalizacion(txtfNUEVOFechaFinalizacionMantenimiento.getText());

        EditadoExitosamente editado = new EditadoExitosamente();

        this.dispose();

        editado.setLocationRelativeTo(null);
        editado.setResizable(false);
        editado.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMatenimientoNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarMatenimientoNuevo;
    private javax.swing.JButton btnVolverInicioEditarManteni;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbNumIdMantenimiento;
    private javax.swing.JTextField txtfNUEVOCedulaPersonaMantenimiento;
    private javax.swing.JTextField txtfNUEVODescripcionMantenimiento;
    private javax.swing.JTextField txtfNUEVOFechaFinalizacionMantenimiento;
    private javax.swing.JTextField txtfNUEVOFinalizadoMantenimiento;
    private javax.swing.JTextField txtfNUEVOHoraFinalizacionMantenimiento;
    private javax.swing.JTextField txtfNUEVONombreMantenimiento;
    private javax.swing.JTextField txtfNUEVOPersonaEncargadaMantenimiento;
    private javax.swing.JTextField txtfNUEVOZonaMantenimiento;
    // End of variables declaration//GEN-END:variables
}
